package sprax.aligns;

import sprax.sprout.Sx;

class LabelAndText {
    String mLabel;
    String mParagraphStrings[];
    LabelAndText(String label, String paragraphs[]) {
        mLabel = label;
        mParagraphStrings = paragraphs;
    }
}

public class DonQ 
{    
    public static final String paraEsGutenberg[] = {
        "Primera parte del ingenioso hidalgo don Quijote de la Mancha"
        , "Capítulo primero."
        , "Que trata de la condición y ejercicio del famoso hidalgo "
        + "don Quijote de la Mancha"
        , "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho " 
        + "tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, " 
        + "rocín flaco y galgo corredor.   Una olla de algo más vaca que carnero, " 
        + "salpicón las más noches, duelos y quebrantos los sábados, lantejas los " 
        + "viernes, algún palomino de añadidura los domingos, consumían las tres " 
        + "partes de su hacienda.  El resto della concluían sayo de velarte, calzas de " 
        + "velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de " 
        + "entresemana se honraba con su vellorí de lo más fino.  Tenía en su casa una " 
        + "ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, " 
        + "y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la " 
        + "podadera.  Frisaba la edad de nuestro hidalgo con los cincuenta años; era de " 
        + "complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo " 
        + "de la caza.  Quieren decir que tenía el sobrenombre de Quijada, o Quesada, " 
        + "que en esto hay alguna diferencia en los autores que deste caso escriben; " 
        + "aunque, por conjeturas verosímiles, se deja entender que se llamaba " 
        + "Quejana.  Pero esto importa poco a nuestro cuento; basta que en la narración " 
        + "dél no se salga un punto de la verdad."
        , 
        "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba " 
        + "ocioso, que eran los más del año, se daba a leer libros de caballerías, con " 
        + "tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la " 
        + "caza, y aun la administración de su hacienda.  Y llegó a tanto su curiosidad "
        + "y desatino en esto, que vendió muchas hanegas de tierra de sembradura para "
        + "comprar libros de caballerías en que leer, y así, llevó a su casa todos "
        + "cuantos pudo haber dellos; y de todos, ningunos le parecían tan bien como "
        + "los que compuso el famoso Feliciano de Silva, porque la claridad de su "
        + "prosa y aquellas entricadas razones suyas le parecían de perlas, y más "
        + "cuando llegaba a leer aquellos requiebros y cartas de desafíos, donde en "
        + "muchas partes hallaba escrito: La razón de la sinrazón que a mi razón se "
        + "hace, de tal manera mi razón enflaquece, que con razón me quejo de la "
        + "vuestra fermosura.  Y también cuando leía: ...los altos cielos que de "
        + "vuestra divinidad divinamente con las estrellas os fortifican, y os hacen "
        + "merecedora del merecimiento que merece la vuestra grandeza."
    };
    

    public static final String paraEsAmazon[] = {
        "Capítulo primero."
        , "Que trata de la condición y ejercicio del famoso hidalgo don Quijote de la Mancha"
        , "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor.  Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda.  El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino.  Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.  Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza.  Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque, por conjeturas verosímiles, se deja entender que se llamaba Quejana.  Pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad."
        , "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso, que eran los más del año, se daba a leer libros de caballerías, con tanta afición y gusto, que olvidó casi de todo punto el ejercicio de la caza, y aun la administración de su hacienda.  Y llegó a tanto su curiosidad y desatino en esto, que vendió muchas hanegas de tierra de sembradura para comprar libros de caballerías en que leer, y así, llevó a su casa todos cuantos pudo haber dellos; y de todos, ningunos le parecían tan bien como los que compuso el famoso Feliciano de Silva, porque la claridad de su prosa y aquellas entricadas razones suyas le parecían de perlas, y más cuando llegaba a leer aquellos requiebros y cartas de desafíos, donde en muchas partes hallaba escrito: La razón de la sinrazón que a mi razón se hace, de tal manera mi razón enflaquece, que con razón me quejo de la vuestra fermosura.  Y también cuando leía: ...los altos cielos que de vuestra divinidad divinamente con las estrellas os fortifican, y os hacen merecedora del merecimiento que merece la vuestra grandeza."
        , "Con estas razones perdía el pobre caballero el juicio, y desvelábase por entenderlas y desentrañarles el sentido, que no se lo sacara ni las entendiera el mesmo Aristóteles, si resucitara para sólo ello.  No estaba muy bien con las heridas que don Belianís daba y recebía, porque se imaginaba que, por grandes maestros que le hubiesen curado, no dejaría de tener el rostro y todo el cuerpo lleno de cicatrices y señales.  Pero, con todo, alababa en su autor aquel acabar su libro con la promesa de aquella inacabable aventura, y muchas veces le vino deseo de tomar la pluma y dalle fin al pie de la letra, como allí se promete; y sin duda alguna lo hiciera, y aun saliera con ello, si otros mayores y continuos pensamientos no se lo estorbaran.  Tuvo muchas veces competencia con el cura de su lugar —que era hombre docto, graduado en Sigüenza—, sobre cuál había sido mejor caballero: Palmerín de Ingalaterra o Amadís de Gaula; mas maese Nicolás, barbero del mesmo pueblo, decía que ninguno llegaba al Caballero del Febo, y que si alguno se le podía comparar, era don Galaor, hermano de Amadís de Gaula, porque tenía muy acomodada condición para todo; que no era caballero melindroso, ni tan llorón como su hermano, y que en lo de la valentía no le iba en zaga."
        , "En resolución, él se enfrascó tanto en su letura, que se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio; y así, del poco dormir y del mucho leer, se le secó el celebro, de manera que vino a perder el juicio.  Llenósele la fantasía de todo aquello que leía en los libros, así de encantamentos como de pendencias, batallas, desafíos, heridas, requiebros, amores, tormentas y disparates imposibles; y asentósele de tal modo en la imaginación que era verdad toda aquella máquina de aquellas sonadas soñadas invenciones que leía, que para él no había otra historia más cierta en el mundo.  Decía él que el Cid Ruy Díaz había sido muy buen caballero, pero que no tenía que ver con el Caballero de la Ardiente Espada, que de sólo un revés había partido por medio dos fieros y descomunales gigantes.  Mejor estaba con Bernardo del Carpio, porque en Roncesvalles había muerto a Roldán el encantado, valiéndose de la industria de Hércules, cuando ahogó a Anteo, el hijo de la Tierra, entre los brazos.  Decía mucho bien del gigante Morgante, porque, con ser de aquella generación gigantea, que todos son soberbios y descomedidos, él solo era afable y bien criado.  Pero, sobre todos, estaba bien con Reinaldos de Montalbán, y más cuando le veía salir de su castillo y robar cuantos topaba, y cuando en allende robó aquel ídolo de Mahoma que era todo de oro, según dice su historia.  Diera él, por dar una mano de coces al traidor de Galalón, al ama que tenía, y aun a su sobrina de añadidura."
        , "En efeto, rematado ya su juicio, vino a dar en el más estraño pensamiento que jamás dio loco en el mundo; y fue que le pareció convenible y necesario, así para el aumento de su honra como para el servicio de su república, hacerse caballero andante, y irse por todo el mundo con sus armas y caballo a buscar las aventuras y a ejercitarse en todo aquello que él había leído que los caballeros andantes se ejercitaban, deshaciendo todo género de agravio, y poniéndose en ocasiones y peligros donde, acabándolos, cobrase eterno nombre y fama.  Imaginábase el pobre ya coronado por el valor de su brazo, por lo menos, del imperio de Trapisonda; y así, con estos tan agradables pensamientos, llevado del estraño gusto que en ellos sentía, se dio priesa a poner en efeto lo que deseaba."
        , "Y lo primero que hizo fue limpiar unas armas que habían sido de sus bisabuelos, que, tomadas de orín y llenas de moho, luengos siglos había que estaban puestas y olvidadas en un rincón.  Limpiólas y aderezólas lo mejor que pudo, pero vio que tenían una gran falta, y era que no tenían celada de encaje, sino morrión simple; mas a esto suplió su industria, porque de cartones hizo un modo de media celada, que, encajada con el morrión, hacían una apariencia de celada entera.  Es verdad que para probar si era fuerte y podía estar al riesgo de una cuchillada, sacó su espada y le dio dos golpes, y con el primero y en un punto deshizo lo que había hecho en una semana; y no dejó de parecerle mal la facilidad con que la había hecho pedazos, y, por asegurarse deste peligro, la tornó a hacer de nuevo, poniéndole unas barras de hierro por de dentro, de tal manera que él quedó satisfecho de su fortaleza; y, sin querer hacer nueva experiencia della, la diputó y tuvo por celada finísima de encaje."
        , "Fue luego a ver su rocín, y, aunque tenía más cuartos que un real y más tachas que el caballo de Gonela, que tantum pellis et ossa fuit, le pareció que ni el Bucéfalo de Alejandro ni Babieca el del Cid con él se igualaban.  Cuatro días se le pasaron en imaginar qué nombre le pondría; porque, según se decía él a sí mesmo, no era razón que caballo de caballero tan famoso, y tan bueno él por sí, estuviese sin nombre conocido; y ansí, procuraba acomodársele de manera que declarase quién había sido, antes que fuese de caballero andante, y lo que era entonces; pues estaba muy puesto en razón que, mudando su señor estado, mudase él también el nombre, y le cobrase famoso y de estruendo, como convenía a la nueva orden y al nuevo ejercicio que ya profesaba.  Y así, después de muchos nombres que formó, borró y quitó, añadió, deshizo y tornó a hacer en su memoria e imaginación, al fin le vino a llamar Rocinante: nombre, a su parecer, alto, sonoro y significativo de lo que había sido cuando fue rocín, antes de lo que ahora era, que era antes y primero de todos los rocines del mundo."
        , "Puesto nombre, y tan a su gusto, a su caballo, quiso ponérsele a sí mismo, y en este pensamiento duró otros ocho días, y al cabo se vino a llamar don Quijote; de donde —como queda dicho— tomaron ocasión los autores desta tan verdadera historia que, sin duda, se debía de llamar Quijada, y no Quesada, como otros quisieron decir.  Pero, acordándose que el valeroso Amadís no sólo se había contentado con llamarse Amadís a secas, sino que añadió el nombre de su reino y patria, por Hepila famosa, y se llamó Amadís de Gaula, así quiso, como buen caballero, añadir al suyo el nombre de la suya y llamarse don Quijote de la Mancha, con que, a su parecer, declaraba muy al vivo su linaje y patria, y la honraba con tomar el sobrenombre della."
        , "Limpias, pues, sus armas, hecho del morrión celada, puesto nombre a su rocín y confirmándose a sí mismo, se dio a entender que no le faltaba otra cosa sino buscar una dama de quien enamorarse; porque el caballero andante sin amores era árbol sin hojas y sin fruto y cuerpo sin alma.  Decíase él a sí: "
        , "— Si yo, por malos de mis pecados, o por mi buena suerte, me encuentro por ahí con algún gigante, como de ordinario les acontece a los caballeros andantes, y le derribo de un encuentro, o le parto por mitad del cuerpo, o, finalmente, le venzo y le rindo, ¿no será bien tener a quien enviarle presentado y que entre y se hinque de rodillas ante mi dulce señora, y diga con voz humilde y rendido: ''Yo, señora, soy el gigante Caraculiambro, señor de la ínsula Malindrania, a quien venció en singular batalla el jamás como se debe alabado caballero don Quijote de la Mancha, el cual me mandó que me presentase ante vuestra merced, para que la vuestra grandeza disponga de mí a su talante''? "
        , "¡Oh, cómo se holgó nuestro buen caballero cuando hubo hecho este discurso, y más cuando halló a quien dar nombre de su dama!  Y fue, a lo que se cree, que en un lugar cerca del suyo había una moza labradora de muy buen parecer, de quien él un tiempo anduvo enamorado, aunque, según se entiende, ella jamás lo supo, ni le dio cata dello.  Llamábase Aldonza Lorenzo, y a ésta le pareció ser bien darle título de señora de sus pensamientos; y, buscándole nombre que no desdijese mucho del suyo, y que tirase y se encaminase al de princesa y gran señora, vino a llamarla Dulcinea del Toboso, porque era natural del Toboso; nombre, a su parecer, músico y peregrino y significativo, como todos los demás que a él y a sus cosas había puesto."
    };
    
    /*
     * John Ormsby translation, public domain (Gutenberg, Amazon, etc.)
     */
    public static final String paraEnOrmsby[] = {
        "VOLUME I."
        , "CHAPTER I."
        , "WHICH TREATS OF THE CHARACTER AND PURSUITS OF THE FAMOUS GENTLEMAN DON "
        + "QUIXOTE OF LA MANCHA"
        , "In a village of La Mancha, the name of which I have no desire to call to "
        + "mind, there lived not long since one of those gentlemen that keep a lance "
        + "in the lance-rack, an old buckler, a lean hack, and a greyhound for "
        + "coursing.  An olla of rather more beef than mutton, a salad on most "
        + "nights, scraps on Saturdays, lentils on Fridays, and a pigeon or so extra "
        + "on Sundays, made away with three-quarters of his income.  The rest of it "
        + "went in a doublet of fine cloth and velvet breeches and shoes to match "
        + "for holidays, while on week-days he made a brave figure in his best "
        + "homespun.  He had in his house a housekeeper past forty, a niece under "
        + "twenty, and a lad for the field and market-place, who used to saddle the "
        + "hack as well as handle the bill-hook.  The age of this gentleman of ours "
        + "was bordering on fifty; he was of a hardy habit, spare, gaunt-featured, a "
        + "very early riser and a great sportsman.  They will have it his surname was "
        + "Quixada or Quesada (for here there is some difference of opinion among "
        + "the authors who write on the subject), although from reasonable "
        + "conjectures it seems plain that he was called Quexana.  This, however, is "
        + "of but little importance to our tale; it will be enough not to stray a "
        + "hair's breadth from the truth in the telling of it."
        
        , "You must know, then, that the above-named gentleman whenever he was at "
        + "leisure (which was mostly all the year round) gave himself up to reading "
        + "books of chivalry with such ardour and avidity that he almost entirely "
        + "neglected the pursuit of his field-sports, and even the management of his "
        + "property; and to such a pitch did his eagerness and infatuation go that "
        + "he sold many an acre of tillageland to buy books of chivalry to read, and "
        + "brought home as many of them as he could get.  But of all there were none "
        + "he liked so well as those of the famous Feliciano de Silva's composition, "
        + "for their lucidity of style and complicated conceits were as pearls in "
        + "his sight, particularly when in his reading he came upon courtships and "
        + "cartels, where he often found passages like \"the reason of the unreason "
        + "with which my reason is afflicted so weakens my reason that with reason I "
        + "murmur at your beauty;\" or again, \"the high heavens, that of your "
        + "divinity divinely fortify you with the stars, render you deserving of the "
        + "desert your greatness deserves.\" Over conceits of this sort the poor "
        + "gentleman lost his wits, and used to lie awake striving to understand "
        + "them and worm the meaning out of them; what Aristotle himself could not "
        + "have made out or extracted had he come to life again for that special "
        + "purpose.  He was not at all easy about the wounds which Don Belianis gave "
        + "and took, because it seemed to him that, great as were the surgeons who "
        + "had cured him, he must have had his face and body covered all over with "
        + "seams and scars.  He commended, however, the author's way of ending his "
        + "book with the promise of that interminable adventure, and many a time was "
        + "he tempted to take up his pen and finish it properly as is there "
        + "proposed, which no doubt he would have done, and made a successful piece "
        + "of work of it too, had not greater and more absorbing thoughts prevented "
        + "him."
        , "Many an argument did he have with the curate of his village (a learned "
        + "man, and a graduate of Siguenza) as to which had been the better knight, "
        + "Palmerin of England or Amadis of Gaul.  Master Nicholas, the village "
        + "barber, however, used to say that neither of them came up to the Knight "
        + "of Phoebus, and that if there was any that could compare with him it was "
        + "Don Galaor, the brother of Amadis of Gaul, because he had a spirit that "
        + "was equal to every occasion, and was no finikin knight, nor lachrymose "
        + "like his brother, while in the matter of valour he was not a whit behind "
        + "him.  In short, he became so absorbed in his books that he spent his "
        + "nights from sunset to sunrise, and his days from dawn to dark, poring "
        + "over them; and what with little sleep and much reading his brains got so "
        + "dry that he lost his wits.  His fancy grew full of what he used to read "
        + "about in his books, enchantments, quarrels, battles, challenges, wounds, "
        + "wooings, loves, agonies, and all sorts of impossible nonsense; and it so "
        + "possessed his mind that the whole fabric of invention and fancy he read "
        + "of was true, that to him no history in the world had more reality in it.  "
        + "He used to say the Cid Ruy Diaz was a very good knight, but that he was "
        + "not to be compared with the Knight of the Burning Sword who with one "
        + "back-stroke cut in half two fierce and monstrous giants.  He thought more "
        + "of Bernardo del Carpio because at Roncesvalles he slew Roland in spite of "
        + "enchantments, availing himself of the artifice of Hercules when he "
        + "strangled Antaeus the son of Terra in his arms.  He approved highly of the "
        + "giant Morgante, because, although of the giant breed which is always "
        + "arrogant and ill-conditioned, he alone was affable and well-bred.  But "
        + "above all he admired Reinaldos of Montalban, especially when he saw him "
        + "sallying forth from his castle and robbing everyone he met, and when "
        + "beyond the seas he stole that image of Mahomet which, as his history "
        + "says, was entirely of gold.  To have a bout of kicking at that traitor of "
        + "a Ganelon he would have given his housekeeper, and his niece into the "
        + "bargain."
        , "In short, his wits being quite gone, he hit upon the strangest notion "
        + "that ever madman in this world hit upon, and that was that he fancied it "
        + "was right and requisite, as well for the support of his own honour as for "
        + "the service of his country, that he should make a knight-errant of "
        + "himself, roaming the world over in full armour and on horseback in quest "
        + "of adventures, and putting in practice himself all that he had read of as "
        + "being the usual practices of knights-errant; righting every kind of "
        + "wrong, and exposing himself to peril and danger from which, in the issue, "
        + "he was to reap eternal renown and fame.  Already the poor man saw himself "
        + "crowned by the might of his arm Emperor of Trebizond at least; and so, "
        + "led away by the intense enjoyment he found in these pleasant fancies, he "
        + "set himself forthwith to put his scheme into execution."
        
        , "The first thing he did was to clean up some armour that had belonged to "
        + "his great-grandfather, and had been for ages lying forgotten in a corner "
        + "eaten with rust and covered with mildew.  He scoured and polished it as "
        + "best he could, but he perceived one great defect in it, that it had no "
        + "closed helmet, nothing but a simple morion.  This deficiency, however, his "
        + "ingenuity supplied, for he contrived a kind of half-helmet of pasteboard "
        + "which, fitted on to the morion, looked like a whole one.  It is true that, "
        + "in order to see if it was strong and fit to stand a cut, he drew his "
        + "sword and gave it a couple of slashes, the first of which undid in an "
        + "instant what had taken him a week to do.  The ease with which he had "
        + "knocked it to pieces disconcerted him somewhat, and to guard against that "
        + "danger he set to work again, fixing bars of iron on the inside until he "
        + "was satisfied with its strength; and then, not caring to try any more "
        + "experiments with it, he passed it and adopted it as a helmet of the most "
        + "perfect construction."
        , "He next proceeded to inspect his hack, which, with more quartos than a "
        + "real and more blemishes than the steed of Gonela, that \"tantum pellis et "
        + "ossa fuit,\" surpassed in his eyes the Bucephalus of Alexander or the "
        + "Babieca of the Cid.  Four days were spent in thinking what name to give "
        + "him, because (as he said to himself) it was not right that a horse "
        + "belonging to a knight so famous, and one with such merits of his own, "
        + "should be without some distinctive name, and he strove to adapt it so as "
        + "to indicate what he had been before belonging to a knight-errant, and "
        + "what he then was; for it was only reasonable that, his master taking a "
        + "new character, he should take a new name, and that it should be a "
        + "distinguished and full-sounding one, befitting the new order and calling "
        + "he was about to follow.  And so, after having composed, struck out, "
        + "rejected, added to, unmade, and remade a multitude of names out of his "
        + "memory and fancy, he decided upon calling him Rocinante, a name, to his "
        + "thinking, lofty, sonorous, and significant of his condition as a hack "
        + "before he became what he now was, the first and foremost of all the hacks "
        + "in the world."
        , "Having got a name for his horse so much to his taste, he was anxious to "
        + "get one for himself, and he was eight days more pondering over this "
        + "point, till at last he made up his mind to call himself \"Don Quixote,\" "
        + "whence, as has been already said, the authors of this veracious history "
        + "have inferred that his name must have been beyond a doubt Quixada, and "
        + "not Quesada as others would have it.  Recollecting, however, that the "
        + "valiant Amadis was not content to call himself curtly Amadis and nothing "
        + "more, but added the name of his kingdom and country to make it famous, "
        + "and called himself Amadis of Gaul, he, like a good knight, resolved to "
        + "add on the name of his, and to style himself Don Quixote of La Mancha, "
        + "whereby, he considered, he described accurately his origin and country, "
        + "and did honour to it in taking his surname from it."
        , "So then, his armour being furbished, his morion turned into a helmet, his "
        + "hack christened, and he himself confirmed, he came to the conclusion that "
        + "nothing more was needed now but to look out for a lady to be in love "
        + "with; for a knight-errant without love was like a tree without leaves or "
        + "fruit, or a body without a soul.  As he said to himself, \"If, for my sins, "
        + "or by my good fortune, I come across some giant hereabouts, a common "
        + "occurrence with knights-errant, and overthrow him in one onslaught, or "
        + "cleave him asunder to the waist, or, in short, vanquish and subdue him, "
        + "will it not be well to have some one I may send him to as a present, that "
        + "he may come in and fall on his knees before my sweet lady, and in a "
        + "humble, submissive voice say, 'I am the giant Caraculiambro, lord of the "
        + "island of Malindrania, vanquished in single combat by the never "
        + "sufficiently extolled knight Don Quixote of La Mancha, who has commanded "
        + "me to present myself before your Grace, that your Highness dispose of me "
        + "at your pleasure'?\" Oh, how our good gentleman enjoyed the delivery of "
        + "this speech, especially when he had thought of some one to call his Lady! "
        + "There was, so the story goes, in a village near his own a very "
        + "good-looking farm-girl with whom he had been at one time in love, though, "
        + "so far as is known, she never knew it nor gave a thought to the matter.  "
        + "Her name was Aldonza Lorenzo, and upon her he thought fit to confer the "
        + "title of Lady of his Thoughts; and after some search for a name which "
        + "should not be out of harmony with her own, and should suggest and "
        + "indicate that of a princess and great lady, he decided upon calling her "
        + "Dulcinea del Toboso--she being of El Toboso--a name, to his mind, "
        + "musical, uncommon, and significant, like all those he had already "
        + "bestowed upon himself and the things belonging to him."
    };
    
    /*
     * John Rutherford translation (Penguin)
     */
    public static final String paraEnRutherford[] = { "CHAPTER I"
    , "Concerning the famous hidalgo Don Quixote de la Mancha's position, character and way of life"
    , "In a village in La Mancha, the name of which I cannot quite recall, there lived not long "
    + "ago one of those country gentlemen or hidalgos who keep a lance in a rack, an ancient "
    + "leather shield, a scrawny hack and a greyhound for coursing.  A midday stew with rather "
    + "more shin of beef than leg of lamb, the leftovers for supper most nights, lardy eggs on "
    + "Saturdays, lentil broth on Fridays and an occasional pigeon as a Sunday treat ate up three-"
    + "quarters of his income.  The rest went on a cape of black broadcloth, with breeches of "
    + "velvet and slippers to match for holy days, and on weekdays he walked proudly in the "
    + "finest homespun.  He maintained a housekeeper the wrong side of forty, a niece the right "
    + "side of twenty and a jack of all trades who was as good at saddling the nag as at plying "
    + "the pruning shears.  Our hidalgo himself was nearly fifty; he had a robust constitution, "
    + "dried-up flesh and a withered face, and he was an early riser and a keen huntsman.  His "
    + "surname's said to have been Quixada, or Quesada (as if he were a jawbone, or a "
    + "cheesecake): concerning this detail there's some discrepancy among the authors who "
    + "have written on the subject, although a credible conjecture does suggest he might have "
    + "been a plaintive Quexana.  But this doesn't matter much, as far as our little tale's "
    + "concerned, provided that the narrator doesn't stray one inch from the truth."
    
    , "Now you must understand that during his idle moments (which accounted for most of the "
    + "year) this hidalgo took to reading books of chivalry with such relish and enthusiasm that "
    + "he almost forgot about his hunting and even running his property, and his foolish "
    + "curiosity reached such extremes that he sold acres of arable land to buy these books of "
    + "chivalry, and took home as many of them as he could find;1 he liked none of them so "
    + "much as those by the famous Feliciano de Silva,2 because the brilliance of the prose and "
    + "all that intricate language seemed a treasure to him, never more so than when he was "
    + "reading those amorous compliments and challenges delivered by letter, in which he often "
    + "found: 'The reason for the unreason to which my reason is subjected, so weakens my reason that "
    + "I have reason to complain of your beauty.' And also when he read: '... the lofty heavens which "
    + "with their stars divinely fortify you in your divinity, and make you meritorious of the "
    + "merits merited by your greatness.' Such subtleties used to drive the poor gentleman to "
    + "distraction, and he would rack his brains trying to understand it all and unravel its "
    + "meaning, something that Aristotle himself wouldn't have been capable of doing even if "
    + "he'd come back to life for this purpose alone.  He wasn't very happy about the wounds "
    + "that Sir Belianis kept on inflicting and receiving, because he imagined that, however "
    + "skilful the doctors who treated him, his face and body must have been covered with "
    + "gashes and scars.  But, in spite of all that, he commended the author for ending his book "
    + "with that promise of endless adventure, and often felt the urge to take up his quill and "
    + "bring the story to a proper conclusion, as is promised there; and no doubt he'd have done "
    + "so, and with success too, if other more important and insistent preoccupations hadn't "
    + "prevented him.  He had frequent arguments with the village priest (a learned man -- a "
    + "Sigüenza graduate no less) about which had been the better knight errant, Palmerin of "
    + "England3 or Amadis of Gaul; but Master Nicolás, the village barber, argued that neither "
    + "of them could hold a candle to the Knight of Phoebus, and that if anyone at all could be "
    + "compared to him it was Don Galaor, Amadis of Gaul's brother, because there was no "
    + "emergency he couldn't cope with: he wasn't one of your pernickety knights, nor was he "
    + "such a blubberer as his brother, and he was every bit his equal as far as courage was "
    + "concerned."
    
    , "In short, our hidalgo was soon so absorbed in these books that his nights were spent "
    + "reading from dusk till dawn, and his days from dawn till dusk, until the lack of sleep and "
    + "the excess of reading withered his brain, and he went mad.  Everything he read in his "
    + "books took possession of his imagination: enchantments, fights, battles, challenges, "
    + "wounds, sweet nothings, love affairs, storms and impossible absurdities.  The idea that "
    + "this whole fabric of famous fabrications was real so established itself in his mind that no "
    + "history in the world was truer for him.  He would declare that El Cid, Ruy Díaz, had been "
    + "an excellent knight, but that he couldn't be compared to the Knight of the Burning "
    + "Sword,4 who with just one back-stroke had split two fierce and enormous giants clean "
    + "down the middle.  He felt happier about Bernardo del Carpio, because he'd slain Roland "
    + "the Enchanted at Roncesvalles, by the same method used by Hercules when he suffocated "
    + "Antaeus, the son of Earth -- with a bear-hug.5 He was full of praise for the giant "
    + "Morgante because, despite belonging to a proud and insolent breed, he alone was affable "
    + "and well-mannered.6 But his greatest favourite was Reynald of Montalban,7 most of all "
    + "when he saw him sallying forth from his castle and plundering all those he met, and when "
    + "in foreign parts he stole that image of Muhammad made of solid gold, as his history "
    + "records.  He'd have given his housekeeper, and even his niece into the bargain, to trample "
    + "the traitor Ganelon in the dust.8"

    , "And so, by now quite insane, he conceived the strangest notion that ever took shape in a "
    + "madman's head, considering it desirable and necessary, both for the increase of his "
    + "honour and for the common good, to become a knight errant, and to travel about the "
    + "world with his armour and his arms and his horse in search of adventures, and to practise "
    + "all those activities that he knew from his books were practised by knights errant, "
    + "redressing all kinds of grievances, and exposing himself to perils and dangers that he "
    + "would overcome and thus gain eternal fame and renown.  The poor man could already see "
    + "himself being crowned Emperor of Trebizond, at the very least, through the might of his "
    + "arm; and so, possessed by these delightful thoughts and carried away by the strange "
    + "pleasure that he derived from them, he hastened to put into practice what he so desired.  "

    , "His first step was to clean a suit of armour that had belonged to his forefathers and that, "
    + "covered in rust and mould, had been standing forgotten in a corner for centuries.  "
    + "He scoured and mended it as best he could; yet he realized that it had one important defect, "
    + "which was that the headpiece was not a complete helmet but just a simple steel cap; he "
    + "was ingenious enough, however, to overcome this problem, constructing out of cardboard "
    + "something resembling a visor and face-guard which, once inserted into the steel cap, gave "
    + "it the appearance of a full helmet.  It's true that, to test its strength and find out whether it "
    + "could safely be exposed to attack, he drew his sword and dealt it two blows, with the first "
    + "of which he destroyed in a second what it had taken him a week to create.  He couldn't "
    + "help being concerned about the ease with which he'd shattered it, and to guard against "
    + "this danger he reconstructed it, fixing some iron bars on the inside, which reassured him "
    + "about its strength; and, preferring not to carry out any further tests, he deemed and "
    + "pronounced it a most excellent visored helmet.  "

    , "Then he went to visit his nag, and although it had more corns than a barleyfield and more "
    + "wrong with it than Gonella's horse, which tantum pellis et ossa fuit,9 it seemed to him "
    + "that neither Alexander's Bucephalus nor the Cid's Babieca was its equal.  He spent four "
    + "days considering what name to give the nag; for (he told himself) it wasn't fitting that the "
    + "horse of such a famous knight errant, and such a fine horse in its own right, too, shouldn't "
    + "have some name of eminence; and so he tried to find one that would express both what it "
    + "had been before it became a knight's horse and what it was now, for it was appropriate "
    + "that, since its master had changed his rank, it too should change its name, and acquire a "
    + "famous and much-trumpeted one, as suited the new order and new way of life he "
    + "professed.  And so, after a long succession of names that he invented, eliminated and "
    + "struck out, added, deleted and remade in his mind and in his imagination, he finally "
    + "decided to call it Rocinante, that is, Hackafore, a name which, in his opinion, was lofty "
    + "and sonorous and expressed what the creature had been when it was a humble hack, "
    + "before it became what it was now - the first and foremost of all the hacks in the world.  "

    , "Having given his horse a name, and one so much to his liking, he decided to give himself "
    + "a name as well, and this problem kept him busy for another eight days, at the end of "
    + "which he decided to call himself Don Quixote, that is, Sir Thighpiece, from which, as has "
    + "already been observed, the authors of this most true history concluded that his surname "
    + "must have been Quixada, and not Quesada as others had affirmed.  Yet remembering that "
    + "brave Amadis hadn't been content to call himself Amadis alone, but had added the name "
    + "of his kingdom and homeland, to make it famous, and had styled himself Amadis of "
    + "Gaul, so Don Quixote, as a worthy knight, decided to add his own country to his name "
    + "and call himself Don Quixote de la Mancha, by doing which, in his opinion, he declared "
    + "in a most vivid manner both his lineage and his homeland, and honoured the latter by "
    + "taking it as his surname."

    , "Having, then, cleaned his armour, turned his steel cap into a visored helmet, baptized his "
    + "nag and confirmed himself, he realized that the only remaining task was to find a lady of "
    + "whom he could be enamoured; for a knight errant without a lady-love is a tree without "
    + "leaves or fruit, a body without a soul.  He said to himself: "

    , "'If, for my wicked sins or my good fortune, I encounter some giant, as knights errant "
    + "usually do, and I dash him down in single combat, or cleave him asunder, or, in short, "
    + "defeat and vanquish him, will it not be proper to have someone to whom I can send him "
    + "as a tribute, so that he can come before my sweet lady and fall to his knees and say in "
    + "humble tones of submission: \"I, my lady, am the giant Caraculiambro,10 the Lord of the "
    + "Isle of Malindrania, vanquished in single combat by the never sufficiently praised knight "
    + "Don Quixote de la Mancha, who has commanded me to present myself before Your "
    + "Highness so that Your Highness may dispose of me as you will\"?' "
    
    , "Oh my, how our worthy knight rejoiced once he'd spoken these words - even more, once "
    + "he'd found someone he could call his lady! The fact was - or so it is generally believed - "
    + "that in a nearby village there lived a good-looking peasant girl, with whom he'd once "
    + "been in love (although it appears that she was never aware of this love, about which he "
    + "never told her).  She was called Aldonza Lorenzo, and this was the woman upon whom it "
    + "seemed appropriate to confer the title of the lady of his thoughts; and seeking a name "
    + "with some affinity with his own, which would also suggest the name of a princess and a "
    + "fine lady, he decided to call her Dulcinea del Toboso, because she was a native of El "
    + "Toboso: a name that, in his opinion, was musical and magical and meaningful, like all the "
    + "other names he'd bestowed upon himself and his possessions."    
};  // END OF paraEnRutherford
    
    /*
     * Charles Jarvis translation (Oxford Classics)
     */
    public static final String paraEnJarvis[] = {    "FIRST PART"
    , "CHAPTER 1 "
    , "Which treats of the quality and manner of life of the renowned gentleman Don Quixote de la Mancha."
    , "IN a village of La Mancha,* the name of which I purposely omit, there lived not long "
    + "ago, one of those gentlemen, who usually keep a lance upon a rack, an old target, a lean "
    + "horse, and a greyhound for coursing.  A dish of boiled meat, consisting of somewhat more "
    + "beef than mutton, the fragments served up cold on most nights, an omelet* on Saturdays, "
    + "lentils on Fridays, and a small pigeon by way of addition on Sundays, consumed three-"
    + "fourths of his income.  The rest was laid out in a surtout of fine black cloth, a pair of "
    + "velvet breeches for holidays, with slippers of the same; and on week-days he prided "
    + "himself in the very best of his own homespun cloth.  His family consisted of a "
    + "housekeeper somewhat above forty, a niece not quite twenty, and a lad for the field and "
    + "the market, who both saddled the horse and handled the pruning-hook.  The age of our "
    + "gentleman bordered upon fifty years.  He was of a robust constitution, spare-bodied, of a "
    + "meagre visage; a very early riser, and a keen sportsman.  It is said his surname was "
    + "Quixada, or Quesada (for in this there is some difference among the authors who have "
    + "written upon this subject), though by probable conjectures it may be gathered that he was "
    + "called Quixana.* But this is of little importance to our story; let it suffice that in relating "
    + "we do not swerve a jot from the truth."
    , "You must know then, that this gentleman aforesaid, at times when he was idle, which was "
    + "most part of the year, gave himself up to the reading of books of chivalry, with so much "
    + "attachment and relish, that he almost forgot all the sports of the field, and even the "
    + "management of his domestic affairs; and his curiosity and extravagant fondness herein "
    + "arrived to that pitch, that he sold many acres of arable land to purchase books of knight-"
    + "errantry, and carried home all he could lay hands on of that kind.  But, among them all, "
    + "none pleased him so much as those composed by the famous Feliciano de Silva: for the "
    + "glaringness of his prose, and the intricacy of his style, seemed to him so many pearls; and "
    + "especially when he came to peruse those love-speeches and challenges, wherein in "
    + "several places he found written: 'The reason of the unreasonable treatment of my reason "
    + "enfeebles my reason in such wise, that with reason I complain of your beauty':* and also "
    + "when he read-'The high heavens that with your divinity divinely fortify you with the "
    + "stars, making you meritorious of the merit merited by your greatness'.  "
    , "With this kind of language the poor gentleman lost his wits, and distracted himself to "
    + "comprehend and unravel their meaning; which was more than Aristotle himself could do, "
    + "were he to rise again from the dead for that purpose alone.  He had some doubt as to the "
    + "dreadful wounds which Don Belianis* gave and received; for he imagined, that "
    + "notwithstanding the most expert surgeons had cured him, his face and whole body must "
    + "still be full of seams and scars.  Nevertheless he commended in his author the concluding "
    + "his book with a promise of that unfinishable adventure: and he often had it in his thoughts "
    + "to take pen in hand, and finish it himself, precisely as it is there promised: which he had "
    + "certainly performed, and successfully too, if other greater and continual cogitations had "
    + "not diverted him.  "
    , "He had frequent disputes with the priest of his village (who was a learned person, and had "
    + "taken his degrees in Sigüenza*) which of the two was the better knight, Palmerin of "
    + "England,* or Amadis de Gaul.* But master Nicholas, barber-surgeon of the same town, "
    + "affirmed, that none ever came up to the Knight of the Sun,* and that if any one could be "
    + "compared to him, it was Don Galaor, brother of Amadis de Gaul; for he was of a "
    + "disposition fit for everything, no finical gentleman, nor such a whimperer as his brother; "
    + "and as to courage, he was by no means inferior to him.  In short, he so bewildered himself "
    + "in this kind of study, that he passed the nights in reading from sunset to sunrise, and the "
    + "days from sunrise to sunset: and thus, through little sleep and much reading, his brain was "
    + "dried up in such a manner, that he came at last to lose his wits.  His imagination was full "
    + "of all that he read in his books, to wit, enchantments, battles, single combats, challenges, "
    + "wounds, courtships, amours, tempests, and impossible absurdities.  And so firmly was he "
    + "persuaded that the whole system of chimeras he read of was true, that he thought no "
    + "history in the world was more to be depended upon.  The Cid Ruy Diaz,* he was wont to "
    + "say, was a very good knight, but not comparable to the Knight of the Burning Sword,* "
    + "who with a single back-stroke cleft asunder two fierce and monstrous giants.  He was "
    + "better pleased with Bernardo del Carpio for putting Orlando the Enchanted to death in "
    + "Roncesvalles, by means of the same stratagem which Hercules used, when he suffocated "
    + "Anteus, son of the Earth, by squeezing him between his arms.* He spoke mighty well of "
    + "the giant Morgante;* for, though he was of that monstrous brood who are always proud "
    + "and insolent, he alone was affable and well-bred: but, above all, he was charmed with "
    + "Reynaldos de Montalvan,* especially when he saw him sallying out of his castle and "
    + "plundering all he met; and when abroad he seized that image of Mahomet, which was all "
    + "of massive gold, as his history records.  He would have given his housekeeper, and niece "
    + "to boot, for a fair opportunity of handsomely kicking the traitor Galalon.* "
   
    , "In fine, having quite lost his wits, he fell into one of the strangest conceits that ever "
    + "entered the head of any madman; which was, that he thought it expedient and necessary, "
    + "as well for the advancement of his own reputation, as for the public good, that he should "
    + "commence knight-errant, and wander through the world, with his horse and arms, in quest "
    + "of adventures, and to put in practice whatever he had read to have been practised by "
    + "knights-errant; redressing all kind of grievances, and exposing himself to danger on all "
    + "occasions; that by accomplishing such enterprises he might acquire eternal fame and "
    + "renown.  The poor gentleman already imagined himself at least crowned Emperor of "
    + "Trapisonda* by the valour of his arm; and thus wrapped up in these agreeable delusions, "
    + "and hurried on by the strange pleasure he took in them, he hastened to put in execution "
    + "what he so much desired.  "
    , "And the first thing he did was, to scour up a suit of armour, which had been his great-"
    + "great-grandfather's, and, being mouldy and rust-eaten, had lain by, many long years, "
    + "forgotten in a corner.  These he cleaned and furbished up the best he could; but he "
    + "perceived they had one grand defect, which was, that, instead of a helmet, they had only a "
    + "simple morion, or steel cap; but he dexterously supplied this want by contriving a sort of "
    + "visor of pasteboard, which, being fixed to the head-piece, gave it the appearance of a "
    + "complete helmet.  It is true, indeed, that, to try its strength, and whether it was proof "
    + "against a cut, he drew his sword, and giving it two strokes, undid in an instant what he "
    + "had been a week in doing.  But not altogether approving of his having broken it to pieces "
    + "with so much ease, to again, fencing it with small bars of iron within, in such a manner, "
    + "that he rested satisfied of its strength; and without caring to make a fresh experiment on "
    + "it, he approved and looked upon it as a most excellent helmet.  "
    , "The next thing he did was to visit his steed; and though his bones stuck out like the "
    + "corners of a real, and he had more faults than Gonela's horse,* which tantum pellis et "
    + "ossa fuit* he fancied that neither Alexander's Bucephalus, nor [the] Cid's Babieca, was "
    + "equal to him.  Four days was he considering what name to give him; for (as he said within "
    + "himself) it was not fit that a horse so good, and appertaining to a knight so famous, "
    + "should be without some name of eminence; and therefore he studied to accommodate him "
    + "with one, which should express what he had been before he belonged to a knight-errant, "
    + "and what he actually now was; for it seemed highly reasonable, if his master changed his "
    + "state, he likewise should change his name, and acquire one famous and high sounding, as "
    + "became the new order, and the new way of life he now professed.  And so, after sundry "
    + "names devised and rejected, liked and disliked again, he concluded at last to call him "
    + "Rosinante;* a name, in his opinion, lofty and sonorous, and at the same time expressive "
    + "of what he had been when he was but a common steed, and before he had acquired his "
    + "present superiority over all the steeds in the world.  "
    , "Having given his horse a name so much to his satisfaction, he resolved to give himself "
    + "one.  This consideration took him up eight days more, and at length he determined to call "
    + "himself Don Quixote; from whence, as is said, the authors of this most true history "
    + "conclude, that his name was certainly Quixada, and not Quesada, as others would have it.  "
    + "But recollecting that the valorous Amadis, not content with the simple appellation of "
    + "Amadis, added thereto the name of his kingdom and native country, in order to render it "
    + "famous, and styled himself Amadis de Gaul; so he, like a good knight did in like manner "
    + "call himself Don Quixote de la Mancha; whereby, in his opinion, he set forth in a very "
    + "lively manner his lineage and country, and did it due honour by taking his surname from "
    + "thence.  "
    , "And now, his armour being furbished up, the morion converted into a perfect helmet, and "
    + "both his steed and himself new-named, he persuaded himself that he wanted nothing but "
    + "to make choice of some lady to be in love with; for a knight-errant without a mistress, "
    + "was a tree without leaves or fruit, and a body without a soul.  "
    , "'If,' said he, 'for the punishment of my sins, or through my good fortune, I should chance "
    + "to meet some giant, as is usual with knightserrant, and should overthrow him in fight, or "
    + "cleave him asunder, or in fine vanquish and force him to yield, will it not be proper to "
    + "have some lady to send him to as a present; that, when he comes before her, he may kneel "
    + "to her sweet ladyship, and with humble and submissive tone, accost her thus: \"Madam, I "
    + "am the Giant Caraculiambro, lord of the island [of] Malindrania, whom the never-"
    + "enough-to-be-praised Don Quixote de la Mancha has overcome in single combat, and has "
    + "commanded to present myself before your ladyship, that your grandeur may dispose of "
    + "me as you think proper\"?'"
    , "Oh! how did our good gentleman exult when he had made this harangue, and especially "
    + "when he had found out a person on whom to confer the title of his mistress; which, it is "
    + "believed, happened thus.  Near the place where he lived, there dwelt a very comely "
    + "country lass, with whom he had formerly been in love; though, as it is supposed, she "
    + "never knew it, nor troubled herself about it.  Her name was Aldonza Lorenzo, and her he "
    + "pitched upon to be the lady of his thoughts; then, casting about for a name, which should "
    + "have some affinity with her own, and yet incline towards that of a great lady or princess, "
    + "he resolved to call her Dulcinea del Toboso (for she was born at that place), a name, to "
    + "his thinking, harmonious, uncommon, and significant, like the rest he had devised for "
    + "himself, and for all that belonged to him."
    };  // END OF paraEnJarvis

    /*
     * Google translation from Amazon/Kindle Spanish text  translation (Google Translate, 2012.04.25)
     */
    public static final String paraEnGoogle[] = {
    "Chapter One."
    , "That is the condition and pursuits of the famous knight "
    + "Don Quixote of La Mancha"
    , "Somewhere in la Mancha, whose name I do not remember, "
    + "not long lived one of those gentlemen of lance and ancient "
    + "shield, a lean hack and a greyhound for coursing.  An olla "
    + "of rather more beef than mutton, a salad most nights, duels "
    + "and on Saturdays, lentils on Fridays, and a pigeon or so extra "
    + "on Sundays, the three parts of his estate.  Other della concluded "
    + "broadcloth gown of velvet breeches and shoes for the holidays, with "
    + "slippers of do the same, , and the days of weekdays were honored with "
    + "vellorí of the finest.  had in his house a housekeeper past forty, a niece "
    + "under twenty, and a farmhand and square, so saddling hack as the billhook.  was "
    + "approaching the age of our gentleman with the fifty years was of a hardy, dry "
    + "meat, lean-faced, very early riser and fond of hunting.  they will have it his "
    + "surname was Quijada or Quesada that here there is some difference in referring "
    + "to this case the authors write, though, for plausible conjecture, it is plain "
    + "they called Quejana.  But this matters little to our story, just as in the story "
    + "of him not to stray a point of truth .  "

    , "It is, therefore, to know that the above named gentleman whenever he was "
    + "idle, which were most of the year was given to reading books of chivalry with "
    + "such ardor and avidity that he almost entirely the exercise of "
    + "hunting, and even the management of his estate.  And it came to his eagerness "
    + "and infatuation go that he sold many an acre of land for planting "
    + "buy books of chivalry to read, and so brought home all "
    + "may have few of them; and all were none he liked so well as "
    + "those who composed the famous Feliciano de Silva, for the glory of his "
    + "entricadas prose and those reasons seemed his pearls, and more "
    + "when he came to read those compliments and cartels, where "
    + "often found passages: The reason for the unreason with which my reason "
    + "ago, so weakens my reason that with reason I murmur at "
    + "your beauty.  And when I read: ... the high heavens that "
    + "your divinity divinely fortify you with the stars, and I do "
    + "deserving of the desert your greatness deserves.  "

    , "With these reasons the poor gentleman lost the trial, and lie awake for "
    + "understand them and worm the meaning, not take it out or the "
    + "understood the Aristotle himself, if only to resurrect it.  It was "
    + "well with the wounds which Don Belianis gave and took, because it "
    + "imagined that, great as he had healed, it would still "
    + "have the face and entire body covered with scars and signs.  But with "
    + "However, he praised its author finish her book with the promise of that "
    + "interminable adventure, and often came desire to take the pen and dalle "
    + "end to the letter, as there is promised, and no doubt it did, "
    + "and still come out with it, if greater and more thoughts are not what "
    + "prevented them.  He had many times with the curate of the place, which was "
    + "learned man, a graduate of Siguenza, to which had been the better knight "
    + "Palmerin of England or Amadis of Gaul, Master Nicholas, barber "
    + "Mesmo people, said neither of them came to the Knight of Phoebus, and if "
    + "one could compare with him, was Don Galaor, the brother of Amadis of Gaul, "
    + "because he was very prosperous condition for all, that gentleman was not "
    + "picky, nor lachrymose like his brother, and in the courage not "
    + "going on behind.  "

    , "In short, he became so absorbed in his letura, which he spent his "
    + "nights reading to dark, cloudy days and in murky, and so, "
    + "little sleep and much reading, he dried his welcome, so come "
    + "lost his wits.  His fancy grew full of everything I read in the "
    + "books, enchantments, quarrels, battles, challenges, "
    + "wounds, compliments, loves, agonies and impossible nonsense, and "
    + "it so possessed his mind that was really all that "
    + "machine invention and fancy he read, which for him "
    + "another story was true in the world.  He used to say the Cid Ruy Diaz "
    + "was a very good gentleman, but that had nothing to do with the Knight "
    + "of the Burning Sword who with one back was cut in half two "
    + "fierce and monstrous giants.  He thought more of Bernardo del Carpio, "
    + "because at Roncesvalles he slew Roland in spite of enchantments, availing himself of the "
    + "artifice of Hercules when he strangled Antaeus the son of Earth, including "
    + "arms.  He said much good of the giant Morgante, because, be "
    + "the giant breed which is always arrogant and insolent, he "
    + "alone was affable and well-bred.  But above all he admired Rinaldo "
    + "of Montalban, especially when he saw him leave his castle and robbing everyone "
    + "he met, and when beyond the seas he stole that image of Mahomet which was all of gold, "
    + "according to his story.  Give him, to give a hand of kicking at that traitor of "
    + "Ganelon, his housekeeper and his niece into the bargain.  "

    , "In truth a, his wits, he hit upon the strangest notion "
    + "ever madman in this world, and was that he fancied it and "
    + "necessary, and to increase their honor and for the service of his "
    + "republic, made ??a knight-errant, and go around the world with its "
    + "weapons and horse to seek adventures and to practice all that "
    + "he had read that the knights exercised, undoing all "
    + "kind of wrong, and exposing himself to danger and where, in the issue, "
    + "reap eternal renown and fame.  Already the poor man crowned by the "
    + "of his arm, at least, the empire of Trebizond, and so, with these as "
    + "pleasant thoughts, born of intense enjoyment that they felt was "
    + "himself forthwith to put his scheme into execution he wanted.  "

    , "The first thing he did was clean up some armor that had belonged to his "
    + "great-grandparents, who, eaten with rust and filled with mildew had been for ages "
    + "lying forgotten in a corner.  He scoured and polished it as best "
    + "he could, but he perceived one great defect in it, had no helmet on "
    + "lace, but a simple morion, but was supplied to this industry, because of "
    + "cartons made ??a kind of half helmet, which, fitted with the helmet, did "
    + "an appearance of entire helmet.  It is true that to see if it was strong and "
    + "could be at risk of a cut, he drew his sword and gave him two "
    + "blows, and the first and at one point broke what had been done in a "
    + "week, and no longer seem ill the ease with which he had made "
    + "pieces, and to guard against that danger he set to work again, "
    + "fixing bars of iron on the inside, so that it was "
    + "satisfied with its strength, and, not wanting to do della new experience, the "
    + "deputed by his helmet and had fine lace.  "

    , "He next proceeded to inspect his hack, and although he had more rooms than a real and more "
    + "blemishes than the horse Gonela that presumption Pellis et ossa fuit, it seemed "
    + "that neither Alexander nor Babieca Bucephalus of the Cid with him matched.  "
    + "Four days were spent in thinking what name to give him because, according "
    + "he himself was said same; horse was not right that a knight so famous, and "
    + "it so good itself, was no distinctive name, and so they, sought "
    + "adapt it so as to indicate what had been before belonging to a "
    + "knight errant, and what was then, for it was only because "
    + "that, his master state, he might transfer the name, and COBRASE "
    + "famous and noise, as befitting the new order and the new year "
    + "already professed.  And so, after many names formed, erased and "
    + "removed, added, melted and turned to do in his memory and imagination, at last "
    + "came to be called Rocinante: name, to his thinking, lofty, sonorous and "
    + "significant than it had been when he was a hack before so now "
    + "was, it was first and foremost of all the hacks in the world.  "

    , "Got a name so much to his taste, his horse, he was anxious himself, "
    + "and this thought lasted eight days, and it finally came to call Don "
    + "Quixote, where, as already mentioned, the authors took time Desta as "
    + "True story, no doubt, was due to call Quijada, and not Quesada "
    + "as others would say.  But, remembering that the valiant Amadis not "
    + "only been content to call Amadis alone, but adding the "
    + "name of his kingdom and country to Hepila famous, and called himself Amadis of Gaul, "
    + "and wanted, like a good knight, add his name to his and "
    + "called Don Quixote of La Mancha, whereby, in his view, he described accurately "
    + "his origin and country, and did honor to take the surname from it.  "

    , "So then, their weapons, made ??the morion helmet, put your name "
    + "hack and he himself confirmed, he implied that he lacked other "
    + "nothing but look for a lady to be in love, because the knight "
    + "without love was like a tree without leaves or fruit and body without soul.  As he said "
    + "themselves: "

    , "'If I, for my sins, or my good fortune, I come by "
    + "there some giant, common occurrence as the Knights "
    + "errant, and demolition of a meeting, or delivery will half of the body, or, "
    + "Finally, I beat you and I pay, will not have someone to send it "
    + "presented and to enter and fall on his knees before my sweet lady, and say "
    + "humble, submissive voice:'' I, madam, I am the giant Caraculiambro, "
    + "Malindrania lord of the island, who vanquished in single combat the "
    + "never sufficiently extolled knight Don Quixote of La Mancha, which I "
    + "ordered me to appear before your Grace, that your highness "
    + "dispose of me at your pleasure''? "

    , "Oh, how our good gentleman enjoyed when he had made ??this speech, "
    + "and when he found one to call his Lady! There was, popular belief, "
    + "that in a village near his own peasant girl had a very good "
    + "Apparently, from which he walked a while in love, though, as is known, "
    + "she never knew, nor given to the matter.  Her name was Aldonza Lorenzo, and to "
    + "this he thought fit to confer the title of Lady of his thoughts, and, "
    + "search for a name that harmony with her own, and should suggest and be "
    + "encaminase of a princess and great lady, came to call her Dulcinea del "
    + "Toboso, she being of El Toboso, name, in his opinion, musician and "
    + "uncommon, and significant, like everyone else that he and his things "
    + "had set.  "
    };


    
    public static final String[] texts[] = 
    {     paraEsGutenberg
        , paraEsAmazon
        , paraEnGoogle
        , paraEnJarvis
        , paraEnOrmsby
        , paraEnRutherford
    };
    
    
    static final LabelAndText EsCervantes = new LabelAndText("Miguel de Cervantes Saavedra", paraEsAmazon);
    static final LabelAndText EnGoogleEs = new LabelAndText("Google Translate", paraEnGoogle);
    static final LabelAndText EnJarvis = new LabelAndText("Charles Jarvis", paraEnJarvis);
    static final LabelAndText EnOrmsby = new LabelAndText("John Ormsby", paraEnOrmsby);
    static final LabelAndText EnRutherford = new LabelAndText("John Rutherford", paraEnRutherford);
    
    LabelAndText sLabeledTexts[] = { EsCervantes, EnJarvis, EnOrmsby, EnRutherford };
    
    public static int unit_test() 
    {
        String  testName = DonQ.class.getName() + ".unit_test";
        Sx.puts(testName + " BEGIN"); 
        
        for (String[] paras : texts) {
            for (int j = 0; j < paras.length; j++)
                Sx.format("%2d  %s\n", j, paras[j]);
            Sx.puts();
        }

        Sx.puts();
        
        Sx.puts(testName + " END");    
        return 0;
    }
    
    public static void main(String[] args) { unit_test(); }
    
}
