package sprax.aligns;

import sprax.sprout.Sx;

public class TextHungerGames 
{    
    //  Suzanne Collins (author)
    public static final String paraEn_1[] = { "Part I"
        , "“THE TRIBUTES”"
        , "1"
        , "When I wake up, the other side of the bed is cold.  My fingers stretch out, seeking Prim’s warmth but finding only the rough canvas cover of the mattress.  She must have had bad dreams and climbed in with our mother.  Of course, she did.  This is the day of the reaping."
        , "I prop myself up on one elbow.  There’s enough light in the bedroom to see them.  My little sister, Prim, curled up on her side, cocooned in my mother’s body, their cheeks pressed together.  In sleep, my mother looks younger, still worn but not so beaten-down.  Prim’s face is as fresh as a raindrop, as lovely as the primrose for which she was named.  My mother was very beautiful once, too.  Or so they tell me."
        , "Sitting at Prim’s knees, guarding her, is the world’s ugliest cat.  Mashed-in nose, half of one ear missing, eyes the color of rotting squash.  Prim named him Buttercup, insisting that his muddy yellow coat matched the bright flower.  He hates me.  Or at least distrusts me.  Even though it was years ago, I think he still remembers how I tried to drown him in a bucket when Prim brought him home.  Scrawny kitten, belly swollen with worms, crawling with fleas.  The last thing I needed was another mouth to feed.  But Prim begged so hard, cried even, I had to let him stay.  It turned out okay.  My mother got rid of the vermin and he’s a born mouser.  Even catches the occasional rat.  Sometimes, when I clean a kill, I feed Buttercup the entrails.  He has stopped hissing at me."
        , "Entrails.  No hissing.  This is the closest we will ever come to love."
        , "I swing my legs off the bed and slide into my hunting boots.  Supple leather that has molded to my feet.  I pull on trousers, a shirt, tuck my long dark braid up into a cap, and grab my forage bag.  On the table, under a wooden bowl to protect it from hungry rats and cats alike, sits a perfect little goat cheese wrapped in basil leaves.  Prim’s gift to me on reaping day.  I put the cheese carefully in my pocket as I slip outside."
        , "Our part of District 12, nicknamed the Seam, is usually crawling with coal miners heading out to the morning shift at this hour.  Men and women with hunched shoulders, swollen knuckles, many who have long since stopped trying to scrub the coal dust out of their broken nails, the lines of their sunken faces.  But today the black cinder streets are empty.  Shutters on the squat gray houses are closed.  The reaping isn’t until two.  May as well sleep in.  If you can."
        , "Our house is almost at the edge of the Seam.  I only have to pass a few gates to reach the scruffy field called the Meadow.  Separating the Meadow from the woods, in fact enclosing all of District 12, is a high chain-link fence topped with barbed-wire loops.  In theory, it’s supposed to be electrified twenty-four hours a day as a deterrent to the predators that live in the woods—packs of wild dogs, lone cougars, bears—that used to threaten our streets.  But since we’re lucky to get two or three hours of electricity in the evenings, it’s usually safe to touch.  Even so, I always take a moment to listen carefully for the hum that means the fence is live.  Right now, it’s silent as a stone.  Concealed by a clump of bushes, I flatten out on my belly and slide under a two-foot stretch that’s been loose for years.  There are several other weak spots in the fence, but this one is so close to home I almost always enter the woods here."
        , "As soon as I’m in the trees, I retrieve a bow and sheath of arrows from a hollow log.  Electrified or not, the fence has been successful at keeping the flesh-eaters out of District 12.  Inside the woods they roam freely, and there are added concerns like venomous snakes, rabid animals, and no real paths to follow.  But there’s also food if you know how to find it.  My father knew and he taught me some before he was blown to bits in a mine explosion.  There was nothing even to bury.  I was eleven then.  Five years later, I still wake up screaming for him to run."
        , "Even though trespassing in the woods is illegal and poaching carries the severest of penalties, more people would risk it if they had weapons.  But most are not bold enough to venture out with just a knife.  My bow is a rarity, crafted by my father along with a few others that I keep well hidden in the woods, carefully wrapped in waterproof covers.  My father could have made good money selling them, but if the officials found out he would have been publicly executed for inciting a rebellion.  Most of the Peacekeepers turn a blind eye to the few of us who hunt because they’re as hungry for fresh meat as anybody is.  In fact, they’re among our best customers.  But the idea that someone might be arming the Seam would never have been allowed."
        , "In the fall, a few brave souls sneak into the woods to harvest apples.  But always in sight of the Meadow.  Always close enough to run back to the safety of District 12 if trouble arises.  “District Twelve.  Where you can starve to death in safety,” I mutter.  Then I glance quickly over my shoulder.  Even here, even in the middle of nowhere, you worry someone might overhear you."
        , "When I was younger, I scared my mother to death, the things I would blurt out about District 12, about the people who rule our country, Panem, from the far-off city called the Capitol.  Eventually I understood this would only lead us to more trouble.  So I learned to hold my tongue and to turn my features into an indifferent mask so that no one could ever read my thoughts.  Do my work quietly in school.  Make only polite small talk in the public market.  Discuss little more than trades in the Hob, which is the black market where I make most of my money.  Even at home, where I am less pleasant, I avoid discussing tricky topics.  Like the reaping, or food shortages, or the Hunger Games.  Prim might begin to repeat my words and then where would we be?"
        , "In the woods waits the only person with whom I can be myself.  Gale.  I can feel the muscles in my face relaxing, my pace quickening as I climb the hills to our place, a rock ledge overlooking a valley.  A thicket of berry bushes protects it from unwanted eyes.  The sight of him waiting there brings on a smile.  Gale says I never smile except in the woods."
        , "“Hey, Catnip,” says Gale.  My real name is Katniss, but when I first told him, I had barely whispered it.  So he thought I’d said Catnip.  Then when this crazy lynx started following me around the woods looking for handouts, it became his official nickname for me.  I finally had to kill the lynx because he scared off game.  I almost regretted it because he wasn’t bad company.  But I got a decent price for his pelt."
        , "“Look what I shot.” Gale holds up a loaf of bread with an arrow stuck in it, and I laugh.  It’s real bakery bread, not the flat, dense loaves we make from our grain rations.  I take it in my hands, pull out the arrow, and hold the puncture in the crust to my nose, inhaling the fragrance that makes my mouth flood with saliva.  Fine bread like this is for special occasions."
        , "“Mm, still warm,” I say.  He must have been at the bakery at the crack of dawn to trade for it.  “What did it cost you?”"
        , "“Just a squirrel.  Think the old man was feeling sentimental this morning,” says Gale.  “Even wished me luck.”"
        , "“Well, we all feel a little closer today, don’t we?” I say, not even bothering to roll my eyes.  “Prim left us a cheese.” I pull it out."
        , "His expression brightens at the treat.  “Thank you, Prim.  We’ll have a real feast.” Suddenly he falls into a Capitol accent as he mimics Effie Trinket, the maniacally upbeat woman who arrives once a year to read out the names at the reaping.  “I almost forgot! Happy Hunger Games!” He plucks a few blackberries from the bushes around us.  “And may the odds—” He tosses a berry in a high arc toward me."
        , "I catch it in my mouth and break the delicate skin with my teeth.  The sweet tartness explodes across my tongue.  “—be ever in your favor!” I finish with equal verve.  We have to joke about it because the alternative is to be scared out of your wits.  Besides, the Capitol accent is so affected, almost anything sounds funny in it."
        , "I watch as Gale pulls out his knife and slices the bread.  He could be my brother.  Straight black hair, olive skin, we even have the same gray eyes.  But we’re not related, at least not closely.  Most of the families who work the mines resemble one another this way."
        , "That’s why my mother and Prim, with their light hair and blue eyes, always look out of place.  They are.  My mother’s parents were part of the small merchant class that caters to officials, Peacekeepers, and the occasional Seam customer.  They ran an apothecary shop in the nicer part of District 12.  Since almost no one can afford doctors, apothecaries are our healers.  My father got to know my mother because on his hunts he would sometimes collect medicinal herbs and sell them to her shop to be brewed into remedies.  She must have really loved him to leave her home for the Seam.  I try to remember that when all I can see is the woman who sat by, blank and unreachable, while her children turned to skin and bones.  I try to forgive her for my father’s sake.  But to be honest, I’m not the forgiving type."
        , "Gale spreads the bread slices with the soft goat cheese, carefully placing a basil leaf on each while I strip the bushes of their berries.  We settle back in a nook in the rocks.  From this place, we are invisible but have a clear view of the valley, which is teeming with summer life, greens to gather, roots to dig, fish iridescent in the sunlight.  The day is glorious, with a blue sky and soft breeze.  The food’s wonderful, with the cheese seeping into the warm bread and the berries bursting in our mouths.  Everything would be perfect if this really was a holiday, if all the day off meant was roaming the mountains with Gale, hunting for tonight’s supper.  But instead we have to be standing in the square at two o’clock waiting for the names to be called out."
        , "“We could do it, you know,” Gale says quietly."
        , "“What?” I ask."
        , "“Leave the district.  Run off.  Live in the woods.  You and I, we could make it,” says Gale."
        , "I don’t know how to respond.  The idea is so preposterous."
        , "“If we didn’t have so many kids,” he adds quickly."
        , "They’re not our kids, of course.  But they might as well be.  Gale’s two little brothers and a sister.  Prim.  And you may as well throw in our mothers, too, because how would they live without us? Who would fill those mouths that are always asking for more? With both of us hunting daily, there are still nights when game has to be swapped for lard or shoelaces or wool, still nights when we go to bed with our stomachs growling."
        , "“I never want to have kids,” I say."
        , "“I might.  If I didn’t live here,” says Gale."
        , "“But you do,” I say, irritated."
        , "“Forget it,” he snaps back."
        , "The conversation feels all wrong.  Leave? How could I leave Prim, who is the only person in the world I’m certain I love? And Gale is devoted to his family.  We can’t leave, so why bother talking about it? And even if we did…even if we did…where did this stuff about having kids come from? There’s never been anything romantic between Gale and me.  When we met, I was a skinny twelve-year-old, and although he was only two years older, he already looked like a man.  It took a long time for us to even become friends, to stop haggling over every trade and begin helping each other out."
        , "Besides, if he wants kids, Gale won’t have any trouble finding a wife.  He’s good-looking, he’s strong enough to handle the work in the mines, and he can hunt.  You can tell by the way the girls whisper about him when he walks by in school that they want him.  It makes me jealous but not for the reason people would think.  Good hunting partners are hard to find."
        , "“What do you want to do?” I ask.  We can hunt, fish, or gather."
        , "“Let’s fish at the lake.  We can leave our poles and gather in the woods.  Get something nice for tonight,” he says."
        , "Tonight.  After the reaping, everyone is supposed to celebrate.  And a lot of people do, out of relief that their children have been spared for another year.  But at least two families will pull their shutters, lock their doors, and try to figure out how they will survive the painful weeks to come."
        , "We make out well.  The predators ignore us on a day when easier, tastier prey abounds.  By late morning, we have a dozen fish, a bag of greens and, best of all, a gallon of strawberries.  I found the patch a few years ago, but Gale had the idea to string mesh nets around it to keep out the animals."
        , "On the way home, we swing by the Hob, the black market that operates in an abandoned warehouse that once held coal.  When they came up with a more efficient system that transported the coal directly from the mines to the trains, the Hob gradually took over the space.  Most businesses are closed by this time on reaping day, but the black market’s still fairly busy.  We easily trade six of the fish for good bread, the other two for salt.  Greasy Sae, the bony old woman who sells bowls of hot soup from a large kettle, takes half the greens off our hands in exchange for a couple of chunks of paraffin.  We might do a tad better elsewhere, but we make an effort to keep on good terms with Greasy Sae.  She’s the only one who can consistently be counted on to buy wild dog.  We don’t hunt them on purpose, but if you’re attacked and you take out a dog or two, well, meat is meat.  “Once it’s in the soup, I’ll call it beef,” Greasy Sae says with a wink.  No one in the Seam would turn up their nose at a good leg of wild dog, but the Peacekeepers who come to the Hob can afford to be a little choosier."
        , "When we finish our business at the market, we go to the back door of the mayor’s house to sell half the strawberries, knowing he has a particular fondness for them and can afford our price.  The mayor’s daughter, Madge, opens the door.  She’s in my year at school.  Being the mayor’s daughter, you’d expect her to be a snob, but she’s all right.  She just keeps to herself.  Like me.  Since neither of us really has a group of friends, we seem to end up together a lot at school.  Eating lunch, sitting next to each other at assemblies, partnering for sports activities.  We rarely talk, which suits us both just fine."
        , "Today her drab school outfit has been replaced by an expensive white dress, and her blonde hair is done up with a pink ribbon.  Reaping clothes."
        , "“Pretty dress,” says Gale."
        , "Madge shoots him a look, trying to see if it’s a genuine compliment or if he’s just being ironic.  It is a pretty dress, but she would never be wearing it ordinarily.  She presses her lips together and then smiles.  “Well, if I end up going to the Capitol, I want to look nice, don’t I?”"
        , "Now it’s Gale’s turn to be confused.  Does she mean it? Or is she messing with him? I’m guessing the second."
        , "“You won’t be going to the Capitol,” says Gale coolly.  His eyes land on a small, circular pin that adorns her dress.  Real gold.  Beautifully crafted.  It could keep a family in bread for months.  “What can you have? Five entries? I had six when I was just twelve years old.”"
        , "“That’s not her fault,” I say."
        , "“No, it’s no one’s fault.  Just the way it is,” says Gale."
        , "Madge’s face has become closed off.  She puts the money for the berries in my hand.  “Good luck, Katniss.”"
        , "“You, too,” I say, and the door closes."
        , "We walk toward the Seam in silence.  I don’t like that Gale took a dig at Madge, but he’s right, of course.  The reaping system is unfair, with the poor getting the worst of it.  You become eligible for the reaping the day you turn twelve.  That year, your name is entered once.  At thirteen, twice.  And so on and so on until you reach the age of eighteen, the final year of eligibility, when your name goes into the pool seven times.  That’s true for every citizen in all twelve districts in the entire country of Panem."
        , "But here’s the catch.  Say you are poor and starving as we were.  You can opt to add your name more times in exchange for tesserae.  Each tessera is worth a meager year’s supply of grain and oil for one person.  You may do this for each of your family members as well.  So, at the age of twelve, I had my name entered four times.  Once, because I had to, and three times for tesserae for grain and oil for myself, Prim, and my mother.  In fact, every year I have needed to do this.  And the entries are cumulative.  So now, at the age of sixteen, my name will be in the reaping twenty times.  Gale, who is eighteen and has been either helping or single-handedly feeding a family of five for seven years, will have his name in forty-two times."
        , "You can see why someone like Madge, who has never been at risk of needing a tessera, can set him off.  The chance of her name being drawn is very slim compared to those of us who live in the Seam.  Not impossible, but slim.  And even though the rules were set up by the Capitol, not the districts, certainly not Madge’s family, it’s hard not to resent those who don’t have to sign up for tesserae."
        , "Gale knows his anger at Madge is misdirected.  On other days, deep in the woods, I’ve listened to him rant about how the tesserae are just another tool to cause misery in our district.  A way to plant hatred between the starving workers of the Seam and those who can generally count on supper and thereby ensure we will never trust one another.  “It’s to the Capitol’s advantage to have us divided among ourselves,” he might say if there were no ears to hear but mine.  If it wasn’t reaping day.  If a girl with a gold pin and no tesserae had not made what I’m sure she thought was a harmless comment."
        , "As we walk, I glance over at Gale’s face, still smoldering underneath his stony expression.  His rages seem pointless to me, although I never say so.  It’s not that I don’t agree with him.  I do.  But what good is yelling about the Capitol in the middle of the woods? It doesn’t change anything.  It doesn’t make things fair.  It doesn’t fill our stomachs.  In fact, it scares off the nearby game.  I let him yell though.  Better he does it in the woods than in the district."
        , "Gale and I divide our spoils, leaving two fish, a couple of loaves of good bread, greens, a quart of strawberries, salt, paraffin, and a bit of money for each."
        , "“See you in the square,” I say."
        , "“Wear something pretty,” he says flatly."
        , "At home, I find my mother and sister are ready to go.  My mother wears a fine dress from her apothecary days.  Prim is in my first reaping outfit, a skirt and ruffled blouse.  It’s a bit big on her, but my mother has made it stay with pins.  Even so, she’s having trouble keeping the blouse tucked in at the back."
        , "A tub of warm water waits for me.  I scrub off the dirt and sweat from the woods and even wash my hair.  To my surprise, my mother has laid out one of her own lovely dresses for me.  A soft blue thing with matching shoes."
        , "“Are you sure?” I ask.  I’m trying to get past rejecting offers of help from her.  For a while, I was so angry, I wouldn’t allow her to do anything for me.  And this is something special.  Her clothes from her past are very precious to her."
        , "“Of course.  Let’s put your hair up, too,” she says.  I let her towel-dry it and braid it up on my head.  I can hardly recognize myself in the cracked mirror that leans against the wall."
        , "“You look beautiful,” says Prim in a hushed voice."
        , "“And nothing like myself,” I say.  I hug her, because I know these next few hours will be terrible for her.  Her first reaping.  She’s about as safe as you can get, since she’s only entered once.  I wouldn’t let her take out any tesserae.  But she’s worried about me.  That the unthinkable might happen."
        , "I protect Prim in every way I can, but I’m powerless against the reaping.  The anguish I always feel when she’s in pain wells up in my chest and threatens to register on my face.  I notice her blouse has pulled out of her skirt in the back again and force myself to stay calm.  “Tuck your tail in, little duck,” I say, smoothing the blouse back in place."
        , "Prim giggles and gives me a small “Quack.”"
        , "“Quack yourself,” I say with a light laugh.  The kind only Prim can draw out of me.  “Come on, let’s eat,” I say and plant a quick kiss on the top of her head."
        , "The fish and greens are already cooking in a stew, but that will be for supper.  We decide to save the strawberries and bakery bread for this evening’s meal, to make it special we say.  Instead we drink milk from Prim’s goat, Lady, and eat the rough bread made from the tessera grain, although no one has much appetite anyway."
        , "At one o’clock, we head for the square.  Attendance is mandatory unless you are on death’s door.  This evening, officials will come around and check to see if this is the case.  If not, you’ll be imprisoned."
        , "It’s too bad, really, that they hold the reaping in the square—one of the few places in District 12 that can be pleasant.  The square’s surrounded by shops, and on public market days, especially if there’s good weather, it has a holiday feel to it.  But today, despite the bright banners hanging on the buildings, there’s an air of grimness.  The camera crews, perched like buzzards on rooftops, only add to the effect."
        , "People file in silently and sign in.  The reaping is a good opportunity for the Capitol to keep tabs on the population as well.  Twelve-through eighteen-year-olds are herded into roped areas marked off by ages, the oldest in the front, the young ones, like Prim, toward the back.  Family members line up around the perimeter, holding tightly to one another’s hands.  But there are others, too, who have no one they love at stake, or who no longer care, who slip among the crowd, taking bets on the two kids whose names will be drawn.  Odds are given on their ages, whether they’re Seam or merchant, if they will break down and weep.  Most refuse dealing with the racketeers but carefully, carefully.  These same people tend to be informers, and who hasn’t broken the law? I could be shot on a daily basis for hunting, but the appetites of those in charge protect me.  Not everyone can claim the same."
        , "Anyway, Gale and I agree that if we have to choose between dying of hunger and a bullet in the head, the bullet would be much quicker."
        , "The space gets tighter, more claustrophobic as people arrive.  The square’s quite large, but not enough to hold District 12’s population of about eight thousand.  Latecomers are directed to the adjacent streets, where they can watch the event on screens as it’s televised live by the state."
        , "I find myself standing in a clump of sixteens from the Seam.  We all exchange terse nods then focus our attention on the temporary stage that is set up before the Justice Building.  It holds three chairs, a podium, and two large glass balls, one for the boys and one for the girls.  I stare at the paper slips in the girls’ ball.  Twenty of them have Katniss Everdeen written on them in careful handwriting."
        , "Two of the three chairs fill with Madge’s father, Mayor Undersee, who’s a tall, balding man, and Effie Trinket, District 12’s escort, fresh from the Capitol with her scary white grin, pinkish hair, and spring green suit.  They murmur to each other and then look with concern at the empty seat."
        , "Just as the town clock strikes two, the mayor steps up to the podium and begins to read.  It’s the same story every year.  He tells of the history of Panem, the country that rose up out of the ashes of a place that was once called North America.  He lists the disasters, the droughts, the storms, the fires, the encroaching seas that swallowed up so much of the land, the brutal war for what little sustenance remained.  The result was Panem, a shining Capitol ringed by thirteen districts, which brought peace and prosperity to its citizens.  Then came the Dark Days, the uprising of the districts against the Capitol.  Twelve were defeated, the thirteenth obliterated.  The Treaty of Treason gave us the new laws to guarantee peace and, as our yearly reminder that the Dark Days must never be repeated, it gave us the Hunger Games."
        , "The rules of the Hunger Games are simple.  In punishment for the uprising, each of the twelve districts must provide one girl and one boy, called tributes, to participate.  The twenty-four tributes will be imprisoned in a vast outdoor arena that could hold anything from a burning desert to a frozen wasteland.  Over a period of several weeks, the competitors must fight to the death.  The last tribute standing wins."
        , "Taking the kids from our districts, forcing them to kill one another while we watch—this is the Capitol’s way of reminding us how totally we are at their mercy.  How little chance we would stand of surviving another rebellion.  Whatever words they use, the real message is clear.  “Look how we take your children and sacrifice them and there’s nothing you can do.  If you lift a finger, we will destroy every last one of you.  Just as we did in District Thirteen.”"
        , "To make it humiliating as well as torturous, the Capitol requires us to treat the Hunger Games as a festivity, a sporting event pitting every district against the others.  The last tribute alive receives a life of ease back home, and their district will be showered with prizes, largely consisting of food.  All year, the Capitol will show the winning district gifts of grain and oil and even delicacies like sugar while the rest of us battle starvation."
        , "“It is both a time for repentance and a time for thanks,” intones the mayor."
        , "Then he reads the list of past District 12 victors.  In seventy-four years, we have had exactly two.  Only one is still alive.  Haymitch Abernathy, a paunchy, middle-aged man, who at this moment appears hollering something unintelligible, staggers onto the stage, and falls into the third chair.  He’s drunk.  Very.  The crowd responds with its token applause, but he’s confused and tries to give Effie Trinket a big hug, which she barely manages to fend off."
        , "The mayor looks distressed.  Since all of this is being televised, right now District 12 is the laughingstock of Panem, and he knows it.  He quickly tries to pull the attention back to the reaping by introducing Effie Trinket."
        , "Bright and bubbly as ever, Effie Trinket trots to the podium and gives her signature, “Happy Hunger Games! And may the odds be ever in your favor!” Her pink hair must be a wig because her curls have shifted slightly off-center since her encounter with Haymitch.  She goes on a bit about what an honor it is to be here, although everyone knows she’s just aching to get bumped up to a better district where they have proper victors, not drunks who molest you in front of the entire nation."
        , "Through the crowd, I spot Gale looking back at me with a ghost of a smile.  As reapings go, this one at least has a slight entertainment factor.  But suddenly I am thinking of Gale and his forty-two names in that big glass ball and how the odds are not in his favor.  Not compared to a lot of the boys.  And maybe he’s thinking the same thing about me because his face darkens and he turns away.  “But there are still thousands of slips,” I wish I could whisper to him."
        , "It’s time for the drawing.  Effie Trinket says as she always does, “Ladies first!” and crosses to the glass ball with the girls’ names.  She reaches in, digs her hand deep into the ball, and pulls out a slip of paper.  The crowd draws in a collective breath and then you can hear a pin drop, and I’m feeling nauseous and so desperately hoping that it’s not me, that it’s not me, that it’s not me."
        , "Effie Trinket crosses back to the podium, smoothes the slip of paper, and reads out the name in a clear voice.  And it’s not me."
        , "It’s Primrose Everdeen."
        , "2"
        , "One time, when I was in a blind in a tree, waiting motionless for game to wander by, I dozed off and fell ten feet to the ground, landing on my back.  It was as if the impact had knocked every wisp of air from my lungs, and I lay there struggling to inhale, to exhale, to do anything."
    };
    
    //  Pilar Ramirez Tello (translator) 
    public static final String paraEsTello[] = { "Para James Proimos"
        , "PRIMERA PARTE"
        , "LOS TRIBUTOS"
        , "1"
        , "Cuando me despierto, el otro lado de la cama está frío.  Estiro los dedos buscando el calor de Prim, pero no encuentro más que la basta funda de lona del colchón.  Seguro que ha tenido pesadillas y se ha metido en la cama de nuestra madre; claro que sí, porque es el día de la cosecha."
        , "Me apoyo en un codo y me levanto un poco; en el dormitorio entra algo de luz, así que puedo verlas.  Mi hermana pequeña, Prim, acurrucada a su lado, protegida por el cuerpo de mi madre, las dos con las mejillas pegadas.  Mi madre parece más joven cuando duerme; agotada, aunque no tan machacada.  La cara de Prim es tan fresca como una gota de agua, tan encantadora como la prímula que le da nombre.  Mi madre también fue muy guapa hace tiempo, o eso me han dicho."
        , "Sentado sobre las rodillas de Prim, para protegerla, está el gato más feo del mundo: hocico aplastado, media oreja arrancada y ojos del color de un calabacín podrido.  Prim le puso Buttercup porque, según ella, su pelaje amarillo embarrado tenía el mismo tono de aquella flor, el ranúnculo.  El gato me odia o, al menos, no confía en mí.  Aunque han pasado ya algunos años, creo que todavía recuerda que intenté ahogarlo en un cubo cuando Prim lo trajo a casa; era un gatito escuálido, con la tripa hinchada por las lombrices y lleno de pulgas.  Lo último que yo necesitaba era otra boca que alimentar, pero mi hermana me suplicó mucho, e incluso lloró para que le dejase quedárselo.  Al final la cosa salió bien: mi madre le libró de los parásitos, y ahora es un cazador de ratones nato; a veces, hasta caza alguna rata.  Como de vez en cuando le echo las entrañas de las presas, ha dejado de bufarme."
        , "Entrañas y nada de bufidos: no habrá más cariño que ése entre nosotros."
        , "Me bajo de la cama y me pongo las botas de cazar; la piel fina y suave se ha adaptado a mis pies.  Me pongo también los pantalones y una camisa, meto mi larga trenza oscura en una gorra y tomo la bolsa que utilizo para guardar todo lo que recojo.  En la mesa, bajo un cuenco de madera que sirve para protegerlo de ratas y gatos hambrientos, encuentro un perfecto quesito de cabra envuelto en hojas de albahaca.  Es un regalo de Prim para el día de la cosecha; cuando salgo me lo meto con cuidado en el bolsillo."
        , "Nuestra parte del Distrito 12, a la que solemos llamar la Veta, está siempre llena a estas horas de mineros del carbón que se dirigen al turno de mañana.  Hombres y mujeres de hombros caídos y nudillos hinchados, muchos de los cuales ya ni siquiera intentan limpiarse el polvo de carbón de las uñas rotas y las arrugas de sus rostros hundidos.  Sin embargo, hoy las calles manchadas de carboncillo están vacías y las contraventanas de las achaparradas casas grises permanecen cerradas.  La cosecha no empieza hasta las dos, así que todos prefieren dormir hasta entonces...  si pueden."
        , "Nuestra casa está casi al final de la Veta, sólo tengo que dejar atrás unas cuantas puertas para llegar al campo desastrado al que llaman la Pradera.  Lo que separa la Pradera de los bosques y, de hecho, lo que rodea todo el Distrito 12, es una alta alambrada metálica rematada con bucles de alambre de espino.  En teoría, se supone que está electrificada las veinticuatro horas para disuadir a los depredadores que viven en los bosques y antes recorrían nuestras calles (jaurías de perros salvajes, pumas solitarios y osos).  En realidad, como, con suerte, sólo tenemos dos o tres horas de electricidad por la noche, no suele ser peligroso tocarla.  Aun así, siempre me tomo un instante para escuchar con atención, por si oigo el zumbido que indica que la valla está cargada.  En este momento está tan silenciosa como una piedra.  Me escondo detrás de un grupo de arbustos, me tumbo boca abajo y me arrastro por debajo de la tira de sesenta centímetros que lleva suelta varios años.  La alambrada tiene otros puntos débiles, pero éste está tan cerca de casa que casi siempre entro en el bosque por aquí."
        , "En cuanto estoy entre los árboles, recupero un arco y un carcaj de flechas que tenía escondidos en un tronco hueco.  Esté o no electrificada, la alambrada ha conseguido mantener a los devoradores de hombres fuera del Distrito 12.  Dentro de los bosques, los animales deambulan a sus anchas y existen otros peligros, como las serpientes venenosas, los animales rabiosos y la falta de senderos que seguir.  Pero también hay comida, si sabes cómo encontrarla.  Mi padre lo sabía y me había enseñado unas cuantas cosas antes de volar en pedazos en la explosión de una mina.  No quedó nada de él que pudiéramos enterrar.  Yo tenía once años; cinco años después, muchas noches me sigo despertando gritándole que corra."
        , "Aunque entrar en los bosques es ilegal y la caza furtiva tiene el peor de los castigos, habría más gente que se arriesgaría si tuviera armas.  El problema es que hay pocos lo bastante valientes para aventurarse armados con un cuchillo.  Mi arco es una rareza que fabricó mi padre, junto con otros similares que guardo bien escondidos en el bosque, envueltos con cuidado en fundas impermeables.  Mi padre podría haber ganado bastante dinero vendiéndolos, pero, de haberlo descubierto los funcionarios del Gobierno, lo habrían ejecutado en público por incitar a la rebelión.  Casi todos los agentes de la paz hacen la vista gorda con los pocos que cazamos, ya que están tan necesitados de carne fresca como los demás.  De hecho, están entre nuestros mejores clientes.  Sin embargo, nunca permitirían que alguien armase a la Veta."
        , "En otoño, unas cuantas almas valientes se internan en los bosques para recoger manzanas, aunque sin perder de vista la Pradera, siempre lo bastante cerca para volver corriendo a la seguridad del Distrito 12 si surgen problemas.  "
        , "—El Distrito 12, donde puedes morirte de hambre sin poner en peligro tu seguridad —murmuro; después miro a mi alrededor rápidamente porque, incluso aquí, en medio de ninguna parte, me preocupa que alguien me escuche."
        , "Cuando era más joven, mataba a mi madre del susto con las cosas que decía sobre el Distrito 12 y la gente que gobierna nuestro país, Panem, desde esa lejana ciudad llamada el Capitolio.  Al final comprendí que aquello sólo podía causarnos más problemas, así que aprendí a morderme la lengua y ponerme una máscara de indiferencia para que nadie pudiese averiguar lo que estaba pensando.  Trabajo en silencio en clase; hago comentarios educados y superficiales en el mercado público; y me limito a las conversaciones comerciales en el Quemador, que es el mercado negro donde gano casi todo mi dinero.  Incluso en casa, donde soy menos simpática, evito entrar en temas espinosos, como la cosecha, los racionamientos de comida o los Juegos del Hambre.  Quizás a Prim se le ocurriera repetir mis palabras y ¿qué sería de nosotras entonces?"
        , "En los bosques me espera la única persona con la que puedo ser yo misma: Gale.  Noto que se me relajan los músculos de la cara, que se me acelera el paso mientras subo por las colinas hasta nuestro lugar de encuentro, un saliente rocoso con vistas al valle.  Un matorral de arbustos de bayas lo protege de ojos curiosos.  Verlo allí, esperándome, me hace sonreír; nunca sonrío, salvo en los bosques."
        , "—Hola, Catnip —me saluda Gale.  "
        , "En realidad me llamo Katniss, como la flor acuática a la que llaman saeta, pero, cuando se lo dije por primera vez, mi voz no era más que un susurro, así que creyó que le decía Catnip, la menta de gato.  Después, cuando un lince loco empezó a seguirme por los bosques en busca de sobras, se convirtió en mi nombre oficial.  Al final tuve que matar al lince porque asustaba a las presas, aunque era tan buena compañía que casi me dio pena.  Por otro lado, me pagaron bien por su piel."
        , "—Mira lo que he cazado.  "
        , "Gale sostiene en alto una hogaza de pan con una flecha clavada en el centro, y yo me río.  Es pan de verdad, de panadería, y no las barras planas y densas que hacemos con nuestras raciones de cereales.  Lo cojo, saco la flecha y me llevo el agujero de la corteza a la nariz para aspirar una fragancia que me hace la boca agua.  El pan bueno como éste es para ocasiones especiales."
        , "—Ummm, todavía está caliente —digo.  Debe de haber ido a la panadería al despuntar el alba para cambiarlo por otra cosa—.  ¿Qué te ha costado?"
        , "—Sólo una ardilla.  Creo que el anciano estaba un poco sentimental esta mañana.  Hasta me deseó buena suerte."
        , "—Bueno, todos nos sentimos un poco más unidos hoy, ¿no? —comento, sin molestarme en poner los ojos en blanco—.  Prim nos ha dejado un queso —digo, sacándolo."
        , "—Gracias, Prim —exclama Gale, alegrándose con el regalo—.  Nos daremos un verdadero festín.  —De repente, se pone a imitar el acento del Capitolio y los ademanes de Effie Trinket, la mujer optimista hasta la demencia que viene una vez al año para leer los nombres de la cosecha—.  ¡Casi se me olvida! ¡Felices Juegos del Hambre! —Recoge unas cuantas moras de los arbustos que nos rodean—.  Y que la suerte...  —empieza, lanzándome una mora.  La cojo con la boca y rompo la delicada piel con los dientes; la dulce acidez del fruto me estalla en la lengua."
        , "—¡...  esté siempre, siempre de vuestra parte! —concluyo, con el mismo brío.  "
        , "Tenemos que bromear sobre el tema, porque la alternativa es morirse de miedo.  Además, el acento del Capitolio es tan afectado que casi todo suena gracioso con él."
        , "Observo a Gale sacar el cuchillo y cortar el pan; podría ser mi hermano: pelo negro liso, piel aceitunada, incluso tenemos los mismos ojos grises.  Pero no somos familia, al menos, no cercana.  Casi todos los que trabajan en las minas tienen un aspecto similar, como nosotros."
        , "Por eso mi madre y Prim, con su cabello rubio y sus ojos azules, siempre parecen fuera de lugar; porque lo están.  Mis abuelos maternos formaban parte de la pequeña clase de comerciantes que sirve a los funcionarios, los agentes de la paz y algún que otro cliente de la Veta.  Tenían una botica en la parte más elegante del Distrito 12; como casi nadie puede permitirse pagar un médico, los boticarios son nuestros sanadores.  Mi padre conoció a mi madre gracias a que, cuando iba de caza, a veces recogía hierbas medicinales y se las vendía a la botica para que fabricaran sus remedios.  Mi madre tuvo que enamorarse de verdad para abandonar su hogar y meterse en la Veta.  Es lo que intento recordar cuando sólo veo en ella a una mujer que se quedó sentada, vacía e inaccesible mientras sus hijas se convertían en piel y huesos.  Intento perdonarla por mi padre, pero, para ser sincera, no soy de las que perdonan."
        , "Gale unta el suave queso de cabra en las rebanadas de pan y coloca con cuidado una hoja de albahaca en cada una, mientras yo recojo bayas de los arbustos.  Nos acomodamos en un rincón de las rocas en el que nadie puede vernos, aunque tenemos una vista muy clara del valle, que está rebosante de vida estival: verduras por recoger, raíces por escarbar y peces irisados a la luz del sol.  El día tiene un aspecto glorioso, de cielo azul y brisa fresca; la comida es estupenda, el pan caliente absorbe el queso y las bayas nos estallan en la boca.  Todo sería perfecto si realmente fuese un día de fiesta, si este día libre consistiese en vagar por las montañas con Gale para cazar la cena de esta noche.  Sin embargo, tendremos que estar en la plaza a las dos en punto para el sorteo de los nombres."
        , "—¿Sabes qué? Podríamos hacerlo —dijo Gale en voz baja."
        , "—¿El qué?"
        , "—Dejar el distrito, huir y vivir en el bosque.  Tú y yo podríamos hacerlo.  —No sé cómo responder, la idea es demasiado absurda—.  Si no tuviésemos tantos niños —añadió él rápidamente."
        , "No son nuestros niños, claro, pero para el caso es lo mismo.  Los dos hermanos pequeños de Gale y su hermana, y Prim.  Nuestras madres también podrían entrar en el lote, porque ¿cómo iban a sobrevivir sin nosotros? ¿Quién alimentaría esas bocas que siempre piden más? Aunque los dos cazamos todos los días, alguna vez tenemos que cambiar las presas por manteca de cerdo, cordones de zapatos o lana, así que hay noches en las que nos vamos a la cama con los estómagos vacíos."
        , "—No quiero tener hijos —digo."
        , "—Puede que yo sí, si no viviese aquí."
        , "—Pero vives aquí —le recuerdo, irritada."
        , "—Olvídalo."
        , "La conversación no va bien.  ¿Irnos? ¿Cómo iba a dejar a Prim, que es la única persona en el mundo a la que estoy segura de querer? Y Gale está completamente dedicado a su familia.  Si no podemos irnos, ¿por qué molestarnos en hablar de eso? Y, aunque lo hiciéramos..., aunque lo hiciéramos..., ¿de dónde ha salido lo de tener hijos? Entre Gale y yo nunca ha habido nada romántico.  Cuando nos conocimos, yo era una niña flacucha de doce años y, aunque él sólo era dos años mayor, ya parecía un hombre.  Nos llevó mucho tiempo hacernos amigos, dejar de regatear en cada intercambio y empezar a ayudarnos mutuamente."
        , "Además, si quiere hijos, Gale no tendrá problemas para encontrar esposa: es guapo, lo bastante fuerte como para trabajar en las minas y capaz de cazar.  Por la forma en que las chicas susurran cuando pasa a su lado en el colegio, está claro que lo desean.  Me pongo celosa, pero no por lo que la gente pensaría, sino porque no es fácil encontrar buenos compañeros de caza."
        , "—¿Qué quieres hacer? —le pregunto, ya que podemos cazar, pescar o recolectar."
        , "—Vamos a pescar en el lago.  Así dejamos las cañas puestas mientras recolectamos en el bosque.  Cogeremos algo bueno para la cena."
        , "La cena.  Después de la cosecha, se supone que todos tienen que celebrarlo, y mucha gente lo hace, aliviada al saber que sus hijos se han salvado un año más.  Sin embargo, al menos dos familias cerrarán las contraventanas y las puertas, e intentarán averiguar cómo sobrevivir a las dolorosas semanas que se avecinan."
        , "Nos va bien; los depredadores no nos hacen caso, porque hoy hay presas más fáciles y sabrosas.  A última hora de la mañana tenemos una docena de peces, una bolsa de verduras y, lo mejor de todo, un buen montón de fresas.  Descubrí el fresal hace unos años y a Gale se le ocurrió la idea de rodearlo de redes para evitar que se acercasen los animales."
        , "De camino a casa pasamos por el Quemador, el mercado negro que funciona en un almacén abandonado en el que antes se guardaba carbón.  Cuando descubrieron un sistema más eficaz que transportaba el carbón directamente de las minas a los trenes, el Quemador fue quedándose con el espacio.  Casi todos los negocios están cerrados a estas horas en un día de cosecha, aunque el mercado negro sigue bastante concurrido.  Cambiamos fácilmente seis de los peces por pan bueno y los otros dos por sal.  Sae la Grasienta, la anciana huesuda que vende cuencos de sopa caliente preparada en un enorme hervidor, nos compra la mitad de las verduras a cambio de un par de trozos de parafina.  Puede que nos hubiese ido mejor en otro sitio, pero nos esforzamos por mantener una buena relación con Sae, ya que es la única que siempre está dispuesta a comprar carne de perro salvaje.  A pesar de que no los cazamos a propósito, si nos atacan y matamos un par, bueno, la carne es la carne.  «Una vez dentro de la sopa, puedo decir que es ternera», dice Sae la Grasienta, guiñando un ojo.  En la Veta, nadie le haría ascos a una buena pata de perro salvaje, pero los agentes de la paz que van al Quemador pueden permitirse ser un poquito más exigentes."
        , "Una vez terminados nuestros negocios en el mercado, vamos a la puerta de atrás de la casa del alcalde para vender la mitad de las fresas, porque sabemos que le gustan especialmente y puede permitirse el precio.  La hija del alcalde, Madge, nos abre la puerta; está en mi clase del colegio.  Podría pensarse que, por ser la hija del alcalde, es una esnob, pero no, sólo es reservada, igual que yo.  Como ninguna de las dos tiene un grupo de amigos, parece que casi siempre acabamos juntas en clase.  Durante la comida, en las reuniones, cuando se hacen grupos para las actividades deportivas...  Apenas hablamos, lo que nos va bien a las dos."
        , "Hoy ha cambiado su soso uniforme del colegio por un caro vestido blanco, y lleva el pelo rubio recogido con un lazo rosa; la ropa de la cosecha."
        , "—Bonito vestido —dice Gale."
        , "Madge lo mira fijamente, mientras intenta averiguar si se trata de un cumplido de verdad o de una ironía.  En realidad, el vestido es bonito, aunque nunca lo habría llevado un día normal.  Aprieta los labios y sonríe."
        , "—Bueno, tengo que estar guapa por si acabo en el Capitolio, ¿no?"
        , "Ahora es Gale el que está desconcertado: ¿lo dice en serio o está tomándole el pelo? Yo creo que es lo segundo."
        , "—Tú no irás al Capitolio —responde Gale con frialdad.  Sus ojos se posan en el pequeño adorno circular que lleva en el vestido; es de oro puro, de bella factura; serviría para dar de comer a una familia entera durante varios meses—.  ¿Cuántas inscripciones puedes tener? ¿Cinco? Yo ya tenía seis con sólo doce años."
        , "—No es culpa suya —intervengo."
        , "—No, no es culpa de nadie.  Las cosas son como son —apostilla Gale."
        , "—Buena suerte, Katniss —dice Madge, con rostro inexpresivo, poniéndome el dinero de las fresas en la mano."
        , "—Lo mismo digo —respondo, y se cierra la puerta."
        , "Caminamos en silencio hacia la Veta.  No me gusta que Gale la haya tomado con Madge, pero tiene razón, por supuesto: el sistema de la cosecha es injusto y los pobres se llevan la peor parte.  Te conviertes en elegible para la cosecha cuando cumples los doce años; ese año, tu nombre entra una vez en el sorteo.  A los trece, dos veces; y así hasta que llegas a los dieciocho, el último año de elegibilidad, y tu nombre entra en la urna siete veces.  El sistema incluye a todos los ciudadanos de los doce distritos de Panem."
        , "Sin embargo, hay gato encerrado.  Digamos que eres pobre y te estás muriendo de hambre, como nos pasaba a nosotras.  Tienes la posibilidad de añadir tu nombre más veces a cambio de teselas; cada tesela vale por un exiguo suministro anual de cereales y aceite para una persona.  También puedes hacer ese intercambio por cada miembro de tu familia, motivo por el que, cuando yo tenía doce años, mi nombre entró cuatro veces en el sorteo.  Una porque era lo mínimo, y tres veces más por las teselas para conseguir cereales y aceite para Prim, mi madre y yo.  De hecho, he tenido que hacer lo mismo todos los años, y las inscripciones en el sorteo son acumulativas.  Por eso, ahora, a los dieciséis años, mi nombre entrará veinte veces en el sorteo de la cosecha.  Gale, que tiene dieciocho y lleva siete años ayudando o alimentando el solo a una familia de cinco, tendrá cuarenta y dos papeletas."
        , "No cuesta entender por qué se enciende con Madge, que nunca ha corrido el peligro de necesitar una tesela.  Las probabilidades de que el nombre de la chica salga elegido son muy reducidas si se comparan con las de los que vivimos en la Veta.  No es imposible, pero sí poco probable y, aunque las reglas las estableció el Capitolio y no los distritos ni, sin duda, la familia de Madge, es difícil no sentir resentimiento hacia los que no tienen que pedir teselas."
        , "Gale es consciente de que su rabia no debería ir contra Madge.  Algunas veces, cuando estamos en lo más profundo del bosque, lo he oído despotricar contra las teselas, diciendo que no son más que otro instrumento para fomentar la miseria en nuestro distrito, una forma de sembrar el odio entre los trabajadores hambrientos de la Veta y los que no suelen tener problemas de comida, y, así, asegurarse de que nunca confiemos los unos en los otros.  «Al Capitolio le viene bien que estemos divididos», me diría, si no hubiese nadie más que yo escuchándolo, si no fuese día de cosecha, si una chica con un alfiler de oro y sin teselas no hubiese hecho lo que seguramente ella consideraba un comentario inofensivo."
        , "Mientras caminamos, lo miro a la cara, todavía ardiendo debajo de su expresión glacial; su ira me parece inútil, aunque no se lo digo.  No es que no esté de acuerdo con él, porque lo estoy, pero ¿de qué sirve despotricar contra el Capitolio en medio del bosque? No cambia nada, no hace que la situación sea más justa y no nos llena el estómago.  De hecho, asusta a las posibles presas.  Sin embargo, lo dejo gritar; mejor hacerlo en el bosque que en el distrito."
        , "Gale y yo nos dividimos el botín, lo que nos deja con dos peces, un par de hogazas de buen pan, verduras, un puñado de fresas, sal, parafina y algo de dinero para cada uno."
        , "—Nos vemos en la plaza —le digo."
        , "—Ponte algo bonito —me responde, sin humor."
        , "En casa, encuentro a mi madre y a mi hermana preparadas para salir.  Mi madre lleva un vestido elegante de sus días de boticaria y Prim viste mi primer traje de cosecha: una falda y una blusa con volantes.  A ella le queda un poco grande, pero mi madre se lo ha sujetado con alfileres; aun así, la blusa se le sale de la falda por la parte de atrás."
        , "Me espera una bañera llena de agua caliente.  Me restriego para quitarme la tierra y el sudor de los bosques, e incluso me lavo el pelo.  Veo, sorprendida, que mi madre me ha sacado uno de sus encantadores vestidos, una suave cosita azul con zapatos a juego."
        , "—¿Estás segura? —le pregunto, porque intento evitar seguir rechazando su ayuda.  "
        , "Antes estaba tan enfadada con ella que no le dejaba hacer nada por mí.  Sin embargo, se trata de algo especial, porque le da mucho valor a la ropa de su pasado."
        , "—Claro que sí, y también me gustaría recogerte el pelo —me responde.  Le dejo secármelo, trenzarlo y colocármelo sobre la cabeza.  Apenas me reconozco en el espejo agrietado que tenemos apoyado en la pared."
        , "—Estás muy guapa —dice Prim, en un susurro."
        , "—Y no me parezco en nada a mí —respondo.  "
        , "La abrazo, porque sé que las horas que nos esperan serán terribles para ella.  Es su primera cosecha, aunque está lo más segura posible, ya que su nombre sólo ha entrado una vez en la urna; no le he dejado pedir ninguna tesela.  Sin embargo, está preocupada por mí, le preocupa que ocurra lo inimaginable."
        , "Protejo a Prim de todas las formas que me es posible, pero nada puedo hacer contra la cosecha.  La angustia que noto en el pecho siempre que mi hermana sufre amenaza con asomar a la superficie.  Me doy cuenta de que se le ha salido de nuevo la blusa por detrás y me obligo a mantener la calma."
        , "—Arréglate la cola, patito —le digo, poniéndole de nuevo la blusa en su sitio."
        , "—Cuac —responde Prim, soltando una risita."
        , "—Eso lo serás tú —añado, riéndome también; ella es la única que puede hacerme reír así—.  Vamos, a comer —digo, dándole un besito rápido en la cabeza."
        , "Decidimos dejar para la cena el pescado y las verduras, que ya se están cocinando en un estofado, y guardamos las fresas y el pan para la noche, diciéndonos que así será algo especial; de modo que bebemos la leche de la cabra de Prim, Lady, y nos comemos el pan basto que hacemos con el cereal de la tesela, aunque, de todos modos, nadie tiene mucho apetito."
        , "A la una en punto nos dirigimos a la plaza.  La asistencia es obligatoria, a no ser que estés a las puertas de la muerte.  Esta noche los funcionarios recorrerán las casas para comprobarlo.  Si alguien ha mentido, lo meterán en la cárcel."
        , "Es una verdadera pena que la ceremonia de la cosecha se celebre en la plaza, uno de los pocos lugares agradables del Distrito 12.  La plaza está rodeada de tiendas y, en los días de mercado, sobre todo si hace buen tiempo, parece que es fiesta.  Sin embargo, hoy, a pesar de los banderines de colores que cuelgan de los edificios, se respira un ambiente de tristeza.  Las cámaras de televisión, encaramadas como águilas ratoneras en los tejados, sólo sirven para acentuar la sensación."
        , "La gente entra en silencio y ficha; la cosecha también es la oportunidad perfecta para que el Capitolio lleve la cuenta de la población.  Conducen a los chicos de entre doce y dieciocho años a las áreas delimitadas con cuerdas y divididas por edades, con los mayores delante y los jóvenes, como Prim, detrás.  Los familiares se ponen en fila alrededor del perímetro, todos cogidos con fuerza de la mano.  También hay otros, los que no tienen a nadie que perder o ya no les importa, que se cuelan entre la multitud para apostar por quiénes serán los dos chicos elegidos.  Se apuesta por la edad que tendrán, por si serán de la Veta o comerciantes, o por si se derrumbarán y se echarán a llorar.  La mayoría se niega a hacer tratos con los mafiosos, salvo con mucha precaución; esas mismas personas suelen ser informadores, y ¿quién no ha infringido la ley alguna vez? Podrían pegarme un tiro todos los días por dedicarme a la caza furtiva, pero los apetitos de los que están al mando me protegen; no todos pueden decir lo mismo."
        , "En cualquier caso, Gale y yo estamos de acuerdo en que, si pudiéramos escoger entre morir de hambre y morir de un tiro en la cabeza, la bala sería mucho más rápida."
        , "La plaza se va llenando, y se vuelve más claustrofóbica conforme llega la gente.  A pesar de su tamaño, no es lo bastante grande para dar cabida a toda la población del Distrito 12, que es de unos ocho mil habitantes.  Los que llegan los últimos tienen que quedarse en las calles adyacentes, desde donde podrán ver el acontecimiento en las pantallas, ya que el Estado lo televisa en directo."
        , "Me encuentro de pie, en un grupo de chicos de dieciséis años de la Veta.  Intercambiamos tensos saludos con la cabeza y centramos nuestra atención en el escenario provisional que han construido delante del Edificio de Justicia.  Allí hay tres sillas, un podio y dos grandes urnas redondas de cristal, una para los chicos y otra para las chicas.  Me quedo mirando los trozos de papel de la bola de las chicas: veinte de ellos tienen escrito con sumo cuidado el nombre de Katniss Everdeen."
        , "Dos de las tres sillas están ocupadas por el alcalde Undersee (el padre de Madge, un hombre alto de calva incipiente) y Effie Trinket, la acompañante del Distrito 12, recién llegada del Capitolio, con su aterradora sonrisa blanca, el pelo rosáceo y un traje verde primavera.  Los dos murmuran entre sí y miran con preocupación el asiento vacío."
        , "Justo cuando el reloj da las dos, el alcalde sube al podio y empieza a leer.  Es la misma historia de todos los años, en la que habla de la creación de Panem, el país que se levantó de las cenizas de un lugar antes llamado Norteamérica.  Enumera la lista de desastres, las sequías, las tormentas, los incendios, los mares que subieron y se tragaron gran parte de la tierra, y la brutal guerra por hacerse con los pocos recursos que quedaron.  El resultado fue Panem, un reluciente Capitolio rodeado por trece distritos, que llevó la paz y la prosperidad a sus ciudadanos.  Entonces llegaron los Días Oscuros, la rebelión de los distritos contra el Capitolio.  Derrotaron a doce de ellos y aniquilaron al decimotercero.  El Tratado de la Traición nos dio unas nuevas leyes para garantizar la paz y, como recordatorio anual de que los Días Oscuros no deben volver a repetirse, nos dio también los Juegos del Hambre."
        , "Las reglas de los Juegos del Hambre son sencillas: en castigo por la rebelión, cada uno de los doce distritos debe entregar a un chico y una chica, llamados tributos, para que participen.  Los veinticuatro tributos se encierran en un enorme estadio al aire libre en la que puede haber cualquier cosa, desde un desierto abrasador hasta un páramo helado.  Una vez dentro, los competidores tienen que luchar a muerte durante un periodo de varias semanas; el que quede vivo, gana."
        , "Coger a los chicos de nuestros distritos y obligarlos a matarse entre ellos mientras los demás observamos; así nos recuerda el Capitolio que estamos completamente a su merced, y que tendríamos muy pocas posibilidades de sobrevivir a otra rebelión.  Da igual las palabras que utilicen, porque el verdadero mensaje queda claro: «Mirad cómo nos llevamos a vuestros hijos y los sacrificamos sin que podáis hacer nada al respecto.  Si levantáis un solo dedo, os destrozaremos a todos, igual que hicimos con el Distrito 13»."
        , "Para que resulte humillante además de una tortura, el Capitolio exige que tratemos los Juegos del Hambre como una festividad, un acontecimiento deportivo en el que los distritos compiten entre sí.  Al último tributo vivo se le recompensa con una vida fácil, y su distrito recibe premios, sobre todo comida.  El Capitolio regala cereales y aceite al distrito ganador durante todo el año, e incluso algunos manjares como azúcar, mientras el resto de nosotros luchamos por no morir de hambre."
        , "—Es el momento de arrepentirse, y también de dar gracias —recita el alcalde."
        , "Después lee la lista de los habitantes del Distrito 12 que han ganado en anteriores ediciones.  En setenta y cuatro años hemos tenido exactamente dos, y sólo uno sigue vivo: Haymitch Abernathy, un barrigón de mediana edad que, en estos momentos, aparece berreando algo ininteligible, se tambalea en el escenario y se deja caer sobre la tercera silla.  Está borracho, y mucho.  La multitud responde con su aplauso protocolario, pero el hombre está aturdido e intenta darle un gran abrazo a Effie Trinket, que apenas consigue zafarse."
        , "El alcalde parece angustiado.  Como todo se televisa en directo, ahora mismo el Distrito 12 es el hazmerreír de Panem, y él lo sabe.  Intenta devolver rápidamente la atención a la cosecha presentando a Effie Trinket."
        , "La mujer, tan alegre y vivaracha como siempre, sube a trote ligero al podio y saluda con su habitual:"
        , "—¡Felices Juegos del Hambre! ¡Y que la suerte esté siempre, siempre de vuestra parte! "
        , "Seguro que su pelo rosa es una peluca, porque tiene los rizos algo torcidos después de su encuentro con Haymitch.  Empieza a hablar sobre el honor que supone estar allí, aunque todos saben lo mucho que desea una promoción a un distrito mejor, con ganadores de verdad, en vez de borrachos que te acosan delante de todo el país."
        , "Localizo a Gale entre la multitud, y él me devuelve la mirada con la sombra de una sonrisa en los labios.  Para ser una cosecha, al menos estaba resultando un poquito divertida.  Pero, de repente, empiezo a pensar en Gale y en las cuarenta y dos veces que aparece su nombre en esa gran bola de cristal, y en cómo la suerte no está siempre de su parte, sobre todo comparado con muchos de los chicos.  Y quizá él esté pensando lo mismo sobre mí, porque se pone serio y aparta la vista."
        , "«No te preocupes, hay mil papeletas», desearía poder decirle."
        , "Ha llegado el momento del sorteo.  Effie Trinket dice lo de siempre, «¡las damas primero!», y se acerca a la urna de cristal con los nombres de las chicas.  Mete la mano hasta el fondo y saca un trozo de papel.  La multitud contiene el aliento, se podría oír un alfiler caer, y yo empiezo a sentir náuseas y a desear desesperadamente que no sea yo, que no sea yo, que no sea yo."
        , "Effie Trinket vuelve al podio, alisa el trozo de papel y lee el nombre con voz clara; y no soy yo."
        , "Es Primrose Everdeen."
        , "2"
        , "Una vez estaba escondida en la rama de un árbol, esperando inmóvil a que apareciese una presa, cuando me quedé dormida y caí al suelo de espaldas desde una altura de tres metros.  Fue como si el impacto me dejase sin una chispa de aire en los pulmones, y allí me quedé, luchando por inspirar, por espirar, por lo que fuera."
    };
    
    
    public static final String[] texts[] = { paraEn_1, paraEsTello };

static final LabelAndText EnCollins = new LabelAndText("Suzanne Collins", paraEn_1);
static final LabelAndText EsTello = new LabelAndText("Pilar Ramirez Tello", paraEsTello);


LabelAndText sLabeledTexts[] = { EnCollins, EsTello };

public static int test_print() 
{
    for (String[] paras : texts) {
        for (int j = 0; j < paras.length; j++)
            Sx.format("%2d  %s\n", j, paras[j]);
        Sx.puts();
    }   
    Sx.puts();
    return 0;
}

public static int unit_test() 
{
    String  testName = TextHungerGames.class.getName() + ".unit_test";
    Sx.puts(testName + " BEGIN"); 
    
    test_print();
    TextAlignment.unit_test();
    
    Sx.puts(testName + " END");    
    return 0;
}

public static void main(String[] args) { unit_test(); }

}
